Repository sile-typesetter/sile, pull requests merged in 2019-11, with the labels that each got.

#708 Fix jbook class
  classes/jbook.lua
  tests/jbook.expected
  tests/jbook.sil
Labels: bug

#712 Use only POSIX compatable shell arguments
  Makefile.am
Labels: packaging

#715 docs(readme): Add explanation about ICU on macOS
  README.md
Labels: documentation

#720 Fix issue number
  README.md
Labels: documentation
