Repository sile-typesetter/sile, pull requests merged in 2019-12, with the labels that each got.

#728 Fix and test parallel package
  packages/parallel.lua
  tests/parallel.expected
  tests/parallel.sil
Labels: bug

#730 Fixed documentation for counters package
  packages/counters.lua
Labels: documentation

#733 chore(tooling): Add dependabot configuration
  .dependabot/config.yml
Labels: enhancement

#745 chore(readme): Add Github Sponsors configuration
  .github/FUNDING.yml
Labels: todo
