Repository sile-typesetter/sile, pull requests merged in 2020-08, with the labels that each got.

#805 Add configure option for LuaJIT
  .luacheckrc
  .travis.yml
  .travis/setup_lua.sh
  Makefile-fonts
  Makefile-luarocks
  configure.ac
  core/sile.lua
  core/utilities.lua
  m4/ax_lua.m4
  packages/frametricks.lua
  packages/rotate.lua
  src/fontmetrics.c
  src/justenoughfontconfig.c
  src/justenoughharfbuzz.c
  src/justenoughicu.c
  src/justenoughlibtexpdf.c
  src/svg.c
Labels: builds & releases, enhancement

#997 Refactor how special commands are handled
  classes/plain.lua
  core/inputs-texlike.lua
  tests/bug-317.expected
Labels: enhancement

#1009 Move PDF specific SVG handling to PDF‌ backend
  core/cairo-output.lua
  core/debug-output.lua
  core/dummy-output.lua
  core/libtexpdf-output.lua
  core/podofo-output.lua
  core/text-output.lua
  packages/svg.lua
Labels: bug

#1010 ci(travis): Revert double fix that broke regular Lua
  .travis/setup_lua.sh
Labels: ci

#1011 Allow scaling SVG's by width, shorten registered command name
  packages/svg.lua
Labels: enhancement

#998 Orient rules relative to writing & page advance directions
  Makefile-fonts
  classes/plain.lua
  core/baseclass.lua
  core/cairo-output.lua
  core/debug-output.lua
  core/dummy-output.lua
  core/libtexpdf-output.lua
  core/nodefactory.lua
  core/podofo-output.lua
  core/text-output.lua
  packages/background.lua
  packages/cropmarks.lua
  packages/grid.lua
  packages/hanmenkyoshi.lua
  packages/image.lua
  packages/pdf.lua
  packages/pdfstructure.lua
  packages/ruby.lua
  packages/rules.lua
  tests/bug-723.expected
  tests/bug-723.sil
  tests/percent-units.expected
Labels: bug

#1014 Match end of passthrough environment commands more robustly
  core/inputs-texlike.lua
  tests/bug-1003.expected
  tests/bug-1003.sil
Labels: bug

#1017 Document better stair logo and \kern command
  documentation/c03-input.sil
  documentation/c06-macroscommands.sil
  documentation/c09-concepts.sil
  documentation/macros.sil
Labels: documentation

#1021 Fixup pullquote package
  classes/plain.lua
  core/libtexpdf-output.lua
  core/nodefactory.lua
  packages/lorem.lua
  packages/pullquote.lua
  packages/ruby.lua
  tests/bug-182.sil
  tests/bug-252.expected
  tests/bug-252.sil
  tests/bug-262.sil
  tests/bug-465-b.sil
  tests/bug-526.sil
  tests/bug-865.expected
  tests/bug-865.sil
  tests/disappearing-skip.sil
  tests/footnote-skip.expected
  tests/footnote-skip.sil
  tests/footnote.expected
  tests/footnote.sil
  tests/ifattop.sil
  tests/linespacing2.sil
  tests/malayalam.sil
  tests/masters.sil
  tests/simplesvg.sil
  tests/split-footnote.expected
  tests/split-footnote.sil
Labels: bug

#1023 fix(core): Don't read zero-length name table entries
  core/opentype-parser.lua
Labels: bug

#1033 Odds and ends
  Makefile.am
Labels: todo

#1031 Refine placement of PDF‌ bookmarks
  classes/book.lua
  packages/pdf.lua
Labels: bug

#1039 Bump assorted dependencies, tooling, and test resources
  Makefile-fonts
  package.json
  sile-dev-1.rockspec
  tests/alignment.expected
  tests/bidi.expected
  tests/bug-283.expected
  tests/bug-61.expected
  tests/bug-865.expected
  tests/counters.expected
  tests/linespacing2.expected
Labels: todo

#1040 Fix hole drawing in SVGs
  core/debug-output.lua
  packages/svg.lua
  src/svg.c
  tests/bug-1005.expected
  tests/bug-1005.sil
  tests/bug-1005.svg
  tests/openpaths.expected
  tests/openpaths.sil
  tests/openpaths.svg
Labels: bug

#1045 Cleanup dependencies and installation related documentation
  .gitignore
  README.md
  documentation/c02-gettingstarted.sil
  package-lock.json
Labels: builds & releases, documentation

#1044 Cleanup libtexpdf outputter
  Makefile.am
  core/cairo-output.lua
  core/debug-output.lua
  core/libtexpdf-output.lua
  core/podofo-output.lua
  core/text-output.lua
  tests/bug-1044.expected
  tests/bug-1044.sil
Labels: bug
