Repository sile-typesetter/sile, pull requests merged in 2020-01, with the labels that each got.

#718 Update Google Groups links
  README.md
Labels: documentation

#752 chore(ci): Setup Github Action to run commitlint
  .github/workflows/commitlint.yml
Labels: ci

#594 some minor corrections for now
  documentation/sile.sil
Labels: documentation

#609 Fix rare crash when font is specified by filename
  core/base-shaper.lua
Labels: bug

#755 test(fonts): Add test for font fallback package with no fallbacks
  tests/font-fallback-empty.expected
  tests/font-fallback-empty.sil
Labels: bug

#757 Fix luarock dependencies and XML based tests
  configure.ac
  sile-dev-1.rockspec
  tests/049EPH.expected
  tests/regressions.pl
Labels: ci, packaging

#758 Set version automatically
  .gitignore
  CHANGELOG.md
  Makefile.am
  bootstrap.sh
  build-aux/adl_recursive_eval.m4
  build-aux/ax_lua.m4
  build-aux/git-version-gen
  configure.ac
  package-lock.json
  package.json
  sile.1.in
  sile.in
Labels: packaging, todo

#760 docs(readme): Cleanup installation related notes
  README.md
Labels: documentation, packaging

#761 Revert "chore(build): Move all auxilary files into same folder"
  configure.ac
  m4/adl_recursive_eval.m4
  m4/ax_lua.m4
Labels: packaging

#762 Man page updates
  .commitlintrc.yml
  configure.ac
  sile.1.in
Labels: documentation

#764 chore(tooling): Add Linguist related repository attributes
  .gitattributes
Labels: todo

#765 fix(core): Guess original parent of split frames post page break
  core/baseclass.lua
  core/frame.lua
  packages/hanmenkyoshi.lua
Labels: bug

#766 Force autoconf and add sile script to install
  Makefile.am
  bootstrap.sh
Labels: packaging

#769 chore(tooling): Drop one-time-use file reader in favor of Lua's builtin
  languages/ug.lua
  languages/unicode.lua
  lua-libraries/char-def.lua
Labels: bug, packaging

#770 Fix differences between make versions and obsolete font URL
  Makefile-fonts
  Makefile.am
Labels: packaging

#771 Bundle busted tests in source releases
  Makefile.am
Labels: packaging

#774 Tweak allowed commit syntax, document
  .commitlintrc.yml
  README.md
Labels: todo

#775 Update Azure builds
  README.md
Labels: ci

#776 Update Travis and delay Lua coverage reporting
  .travis.yml
  README.md
Labels: ci

#777 Match space and breaks in text output to approximate PDF
  core/text-output.lua
Labels: bug

#780 Add Docker manifest
  .commitlintrc.yml
  .dockerignore
  .gitignore
  Dockerfile
  Makefile-fonts
  Makefile.am
  README.md
  build-aux/docker-entrypoint.sh
  build-aux/docker-yay-runner.sh
Labels: packaging

#784 Docker touchups
  .dockerignore
  .gitignore
  Dockerfile
  Makefile.am
  README.md
Labels: bug, packaging

#786 Add method to inject fonts into Docker container
  Dockerfile
  README.md
  build-aux/docker-fontconfig.conf
Labels: packaging

#789 fix(nodes): Fix pushHbox() regression, recognize zerohoxes
  core/typesetter.lua
Labels: bug

#790 chore(docker): Refresh package index before installations
  build-aux/docker-yay-runner.sh
Labels: ci

#701 Add deprecation notices to retired length functions
  classes/pecha.lua
  classes/plain.lua
  core/baseclass.lua
  core/length.lua
  core/measurement.lua
  core/pango-shaper.lua
  core/utilities.lua
  packages/balanced-frames.lua
  packages/chordmode.lua
  packages/footnotes.lua
  packages/hanmenkyoshi.lua
  packages/infonode.lua
  packages/leaders.lua
  packages/linespacing.lua
  packages/pagebuilder-bestfit.lua
  packages/parallel.lua
  packages/pullquote.lua
  packages/rebox.lua
  packages/rules.lua
  packages/specimen.lua
  packages/svg.lua
  packages/tate.lua
  spec/break_spec.lua
  spec/measurements_spec.lua
  tests/classes/testsidenote.lua
  tests/footnote-skip.sil
Labels: enhancement

#791 Deprecate node instantiators
  classes/bible.lua
  classes/book.lua
  classes/jbook.lua
  classes/jplain.lua
  classes/letter.lua
  classes/pecha.lua
  classes/plain.lua
  classes/triglot.lua
  core/baseclass.lua
  core/hyphenator-liang.lua
  core/nodefactory.lua
  languages/my.lua
  languages/ug.lua
  languages/unicode.lua
  packages/bidi.lua
  packages/boustrophedon.lua
  packages/color-fonts.lua
  packages/gutenberg.lua
  packages/indexer.lua
  packages/parallel.lua
  packages/pullquote.lua
  packages/simpletable.lua
  packages/tableofcontents.lua
  packages/tate.lua
  packages/verbatim.lua
  spec/break_spec.lua
  spec/nodefactory_spec.lua
  tests/bug-255.sil
  tests/bug-255b.sil
  tests/classes/testsidenote.lua
Labels: documentation

#792 Cleanup build time warning messages
  Makefile.am
  bootstrap.sh
  configure.ac
  src/Makefile.am
Labels: enhancement, packaging

#793 chore(docker): Don't use URLs from pacman cache from previous builds
  Dockerfile
  build-aux/docker-yay-runner.sh
Labels: ci, packaging

#796 ci(cirrus): Add CI testing on FreeBSD with system luarocks
  .cirrus.yml
  .commitlintrc.yml
Labels: ci, enhancement

#800 ci(docker): Be more aggressive in cache-busting in Docker layers
  Dockerfile
  build-aux/docker-yay-runner.sh
Labels: ci

#801 Add more Pandoc goodies
  packages/pandoc.lua
Labels: enhancement

#803 fix(build): Fix version detection in sparse git checkouts
  build-aux/git-version-gen
Labels: packaging
