Repository sile-typesetter/sile, pull requests merged in 2020-11, with the labels that each got.

#1105 Update CI workflows (action versions and syntax, Docker overhaul)
  .github/workflows/build.yml
  .github/workflows/commitlint.yml
  .github/workflows/deploy.yml
  .github/workflows/luacheck.yml
  .github/workflows/versioning.yml
  Dockerfile
Labels: builds & releases, ci

#1099 Fix LuaRocks installation commands in docs
  README.md
  documentation/c02-gettingstarted.sil
Labels: bug, documentation

#1102 Turn off complex flag for items in \latin-in-tate
  packages/tate.lua
  tests/bug-1101.expected
  tests/bug-1101.sil
Labels: bug

#1110 Allow package load after class init
  classes/book.lua
  classes/plain.lua
  core/baseclass.lua
  core/libtexpdf-output.lua
  core/sile.lua
  packages/footnotes.lua
  packages/simpletable.lua
  tests/bug-244.expected
  tests/parallel.sil
Labels: enhancement
