Repository sile-typesetter/sile, pull requests merged in 2020-02, with the labels that each got.

#808 %fw ⇒ %fh
  documentation/sile.sil
Labels: documentation

#813 chore(tooling): Bump release management tooling versions
  package-lock.json
  package.json
Labels: ci, todo

#814 docs(manual): comand → command, instalation → installation
  documentation/sile.sil
Labels: documentation

#804 Setup Ubuntu packaging
  .gitignore
  Makefile.am
  README.md
  m4/ax_lua.m4
  sile-dev-1.rockspec
Labels: packaging

#818 fix(build): Fix version detection in sparse git checkouts (#803)
  build-aux/git-version-gen
Labels: enhancement, packaging

#822 fix(tooling): Add missing lua-cosmo dependency for Markdown class
  Dockerfile
  configure.ac
  sile-dev-1.rockspec
Labels: bug, packaging

#828 chore(build): Add script to generate homebrew formula
  build-aux/create-homebrew-formula.pl
Labels: packaging

#829 Cleanup measurement stragglers
  packages/pdf.lua
  packages/ruby.lua
  packages/tate.lua
Labels: bug, documentation

#834 Optimize Docker building process
  Dockerfile
  Makefile.am
  build-aux/docker-yay-runner.sh
Labels: ci, packaging
