Repository sile-typesetter/sile, pull requests merged in 2020-07, with the labels that each got.

#874 Cleanup width calculations in leaders, especially dotfill
  packages/leaders.lua
  tests/bug-243.expected
  tests/bug-243.sil
  tests/bug-859.expected
  tests/bug-859.sil
Labels: bug

#899 fix(build): Check for luarocks if not configured --with-system-luarocks
  configure.ac
Labels: packaging

#898 Allow passing nil to process function
  core/inputs-common.lua
  tests/bug-892.expected
  tests/bug-892.sil
Labels: bug

#900 Fix Cirrus builds (FreeBSD)
  .cirrus.yml
Labels: ci

#830 Avoid downloading things we don't need, install things we do
  Makefile-fonts
  Makefile.am
Labels: ci, documentation, packaging

#904 feat(build): Add `make check` fast self-check target
  Makefile.am
Labels: packaging

#910 Revisit bug 892 for case of macros
  core/baseclass.lua
  tests/bug-892.expected
  tests/bug-892.sil
Labels: bug

#914 Fix frame rotation
  packages/rotate.lua
  tests/rotate.sil
Labels: bug

#903 Build & publish releases in GH Actions
  .commitlintrc.yml
  .github/workflows/build.yml
  .github/workflows/commitlint.yml
  .github/workflows/luacheck.yml
  Makefile.am
  README.md
  build-aux/create-homebrew-formula.pl
  configure.ac
Labels: packaging, todo

#909 Test & build against latest versions of stuff
  .commitlintrc.yml
  .dependabot/config.yml
  .github/workflows/luacheck.yml
  .gitignore
  .luacheckrc
  .travis.yml
  .travis/setup_lua.sh
  Makefile.am
  sile-dev-1.rockspec
Labels: ci, packaging

#933 fix(packages): Tate should not affect document language (#932)
  packages/tate.lua
Labels: bug

#946 Install manual in distro-configurable location
  .github/workflows/build.yml
  .gitignore
  .travis.yml
  Makefile-fonts
  Makefile.am
  configure.ac
  examples/showoff.sil
  examples/simple.pdf
  examples/test.pdf
  examples/test.sil
Labels: packaging

#948 Editing pass on chapters 1-5
  Makefile-fonts
  Makefile.am
  classes/docbook.sil
  documentation/c02-gettingstarted.sil
  documentation/c03-input.sil
  documentation/c04-useful.sil
  examples/docbook/article-template.pdf
  package-lock.json
  package.json
  packages/boustrophedon.lua
  packages/frametricks.lua
  packages/infonode.lua
  packages/leaders.lua
  packages/rebox.lua
  packages/svg.lua
  packages/verbatim.lua
Labels: documentation, packaging

#953 Remove (most) of the wildcard hacks from automake
  .github/workflows/build.yml
  Makefile-luarocks
  Makefile.am
  bootstrap.sh
  build-aux/list-dist-files.sh
Labels: ci, packaging

#956 Fix Docker builds
  Dockerfile
  Makefile.am
  README.md
  build-aux/docker-entrypoint.sh
Labels: bug, packaging

#957 Refactor Lua bitwise operations using explicit shim
  .luacheckrc
  configure.ac
  core/harfbuzz-shaper.lua
  core/sile.lua
  core/utilities.lua
  lua-libraries/bitshim.lua
Labels: todo

#958 Fix build on BSDs
  .cirrus.yml
  .github/workflows/build.yml
  Makefile-luarocks
  Makefile.am
  bootstrap.sh
  build-aux/list-dist-files.sh
  configure.ac
  sile-dev-1.rockspec
Labels: packaging

#929 Support Lua 5.4
  .travis.yml
  .travis/setup_lua.sh
  Makefile-luarocks
  sile-dev-1.rockspec
Labels: ci, packaging, todo

#965 Simplify what make has to do
  .cirrus.yml
  .github/workflows/build.yml
  .gitignore
  .luacheckrc
  .travis.yml
  Makefile-luarocks
  Makefile.am
  bootstrap.sh
  build-aux/decore-automake.sh
  build-aux/list-dist-files.sh
  configure.ac
  package.json
Labels: ci, packaging

#973 Allow alternate syntax for multiple debug flags, expand debug documentation
  core/libtexpdf-output.lua
  core/sile.lua
  documentation/c12-tricks.sil
  packages/chapterverse.lua
Labels: documentation, enhancement

#974 Fix #532 by sorting table keys when processing content
  core/hyphenator-liang.lua
  core/nodefactory.lua
  core/utilities.lua
  packages/inputfilter.lua
Labels: bug

#969 fix(build): Ship blank lua_modules install list in source packges
  .github/workflows/build.yml
  Dockerfile
  Makefile-fonts
  Makefile-luarocks
  Makefile.am
  bootstrap.sh
  build-aux/decore-automake.sh
  build-aux/list-dist-files.sh
Labels: bug, builds & releases

#981 fix(packages): Combine unichar output with existing unshaped node
  packages/unichar.lua
  tests/bug-979.expected
  tests/bug-979.sil
Labels: bug

#595 Cleanup examples/test.sil
  Makefile-fonts
  README.md
  examples/book.png
  examples/book.sil
  examples/test.sil
Labels: documentation

#624 Cleanup showoff document
  classes/plain.lua
  core/baseclass.lua
  examples/showoff.sil
Labels: documentation

#983 Test using latest Harfbuzz
  .travis.yml
  tests/bug-308.expected
  tests/bug-308.sil
  tests/bug-526.expected
  tests/bug-526.sil
Labels: ci

#785 Fix Coveralls test coverage reporting
  .travis.yml
  .travis/setup_harfbuzz.sh
  .travis/setup_lua.sh
  Makefile.am
  tests/bug-248.sil
Labels: ci

#988 fix(utilities): Use deterministic sort for sorted pairs
  core/utilities.lua
Labels: bug

#993 fix(languages): Stop Japanese resetting global chapter post macro
  languages/ja.lua
  tests/bug-990.expected
  tests/bug-990.sil
Labels: bug

#987 Add makedefault and set args to SILE.settings.set() and reset option to \set
  classes/plain.lua
  core/base-shaper.lua
  core/baseclass.lua
  core/break.lua
  core/font.lua
  core/harfbuzz-shaper.lua
  core/settings.lua
  core/typesetter.lua
  core/utilities.lua
  documentation/c07-settings.sil
  languages/am.lua
  languages/ug.lua
  packages/chordmode.lua
  packages/insertions.lua
  packages/linespacing.lua
  packages/ruby.lua
  tests/settings.expected
  tests/settings.sil
Labels: enhancement

#996 ci(cirrus): Cache downloads and extracted fonts
  .cirrus.yml
Labels: ci

#999 Use cluacov instead of just luacov for coverage tests
  .gitignore
  .travis.yml
Labels: ci
