Repository sile-typesetter/sile, pull requests merged in 2020-09, with the labels that each got.

#1046 Setup use *as* a GitHub Action
  .github/workflows/deploy.yml
  .github/workflows/versioning.yml
  Dockerfile
  Makefile.am
  README.md
  action.yml
  documentation/c02-gettingstarted.sil
Labels: enhancement

#1057 Remove extra space in \code from packages/url
  packages/url.lua
Labels: bug

#1063 docs(manual): Fix two-column layout example
  documentation/c09-concepts.sil
Labels: documentation

#1064 Papersize before frames
  Makefile.am
  classes/bible.lua
  classes/book.lua
  classes/diglot.lua
  classes/docbook.lua
  classes/jbook.lua
  classes/jplain.lua
  classes/letter.lua
  classes/markdown.lua
  classes/pecha.lua
  classes/plain.lua
  classes/triglot.lua
  core/baseclass.lua
  core/inputs-common.lua
  documentation/c10-classdesign.sil
  documentation/c12-tricks.sil
  examples/bible/usx/classes/usx.lua
  examples/greek-lexicon/classes/perseus.lua
  packages/hanmenkyoshi.lua
  packages/masters.lua
  tests/bug-248.sil
  tests/classes/testsidenote.lua
  tests/classes/testtwocol.lua
  tests/jbook.expected
Labels: bug, documentation

#1066 Patch Penlight usage for forward support
  core/tracestack.lua
Labels: bug

#1068 chore(actions): Rename GH action to not match somebody's username
  action.yml
Labels: ci, todo
