Repository sile-typesetter/sile, pull requests merged in 2021-02, with the labels that each got.

#1127 Redo CLI arg parsing without stdlib
  core/inputs-common.lua
  core/sile.lua
  sile.in
Labels: todo

#1136 Re-enable access to repl, broken in previous release
  core/sile.lua
Labels: bug

#1129 Replace Travis with GH Actions for testing matrix
  .github/workflows/test.yml
  .travis.yml
  .travis/fold_unless_fail
  .travis/setup_harfbuzz.sh
  .travis/setup_lua.sh
  Makefile.am
  README.md
  build-aux/adl_recursive_eval.m4
  build-aux/ax_lua.m4
  configure.ac
Labels: ci, todo

#1134 Overhaul Docker build
  Dockerfile
  Makefile.am
  build-aux/bootstrap-docker.sh
  hooks/build
Labels: builds & releases

#1139 Fix BiDi test using correct font download
  Makefile-fonts
Labels: builds & releases, ci

#1141 fix(docker): Use patched glibc to work around outdated hosts
  Dockerfile
  Makefile.am
  build-aux/bootstrap-docker.sh
  build-aux/docker-bootstrap.sh
  build-aux/docker-glibc-workaround.sh
Labels: builds & releases, ci, todo

#1144 Add font hooks, auto-load color-fonts
  core/font.lua
  documentation/c05-packages.sil
  packages/color-fonts.lua
  tests/bug-1142.expected
  tests/bug-1142.sil
Labels: enhancement
