Repository sile-typesetter/sile, pull requests merged in 2021-09, with the labels that each got.

#1207 Document SILE hitting the official Arch Linux repositories
  README.md
  documentation/c02-gettingstarted.sil
Labels: documentation

#1103 Native math typesetting support
  .commitlintrc.yml
  Makefile-fonts
  core/inputs-texlike.lua
  core/libtexpdf-output.lua
  core/opentype-parser.lua
  core/parserbits.lua
  documentation/c05-packages.sil
  packages/math.lua
  packages/math/base-elements.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
  packages/math/unicode-symbols.lua
  src/justenoughharfbuzz.c
  tests/math-bigops.expected
  tests/math-bigops.xml
  tests/math-fractions.expected
  tests/math-fractions.xml
  tests/math-macros.expected
  tests/math-macros.sil
  tests/math-stretchy.expected
  tests/math-stretchy.xml
  tests/math-subsup.expected
  tests/math-subsup.xml
  tests/math-tables-mathml.expected
  tests/math-tables-mathml.xml
  tests/math-tables-tex.expected
  tests/math-tables-tex.sil
  tests/math-variants.expected
  tests/math-variants.xml
Labels: enhancement

#1232 Correct Armenian support to use ISO 639 code ‘hy’
  core/languages.lua
  languages/hy.lua
Labels: bug

#1235 Make docs match actual CLI behavior
  core/sile.lua
  sile.1.in
Labels: documentation

#1237 ci(azure): Disable Windows CI until somebody actually works on it
  azure-pipelines.yml
Labels: ci

#1231 Add flake.nix and other files
  .gitignore
  Makefile.am
  README.md
  default.nix
  documentation/c02-gettingstarted.sil
  flake.lock
  flake.nix
  libtexpdf.git-rev
  shell.nix
Labels: enhancement

#1233 feat(packages): URLs are allowed many more breakpoints
  packages/url.lua
Labels: enhancement, packages

#1243 fix(shaper): Fix memory leak in Harfbuzz library
  src/justenoughharfbuzz.c
Labels: bug

#1240 Implement and use munder and mover
  packages/math/base-elements.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
  packages/math/unicode-symbols.lua
  tests/math-bigops.expected
  tests/math-bigops.xml
Labels: enhancement

#1215 Add Symbola as fallback for math in code samples
  Makefile.am
  classes/jplain.lua
  core/base-shaper.lua
  core/baseclass.lua
  core/languages.lua
  documentation/c08-language.sil
  languages/ja.lua
  packages/autodoc.lua
  packages/color-fonts.lua
  packages/font-fallback.lua
  packages/math.lua
  packages/ruby.lua
  packages/tate.lua
  tests/bug-244.expected
  tests/bug-244.sil
Labels: documentation

#1254 fix(packages): Don't over-isolate functions run in Pandoc imports
  core/settings.lua
  packages/pandoc.lua
Labels: bug
