Repository sile-typesetter/sile, pull requests merged in 2021-03, with the labels that each got.

#1002 \font-feature
  core/debug-output.lua
  core/font.lua
  packages/features.lua
  tests/font-features-cvXX.expected
  tests/font-features-cvXX.sil
  tests/font-features.expected
  tests/font-features.sil
Labels: enhancement

#1153 Bump CI actions and developer deps
  .commitlintrc.yml
  .github/dependabot.yml
  .github/workflows/commitlint.yml
  package.json
Labels: builds & releases, todo

#1148 feat(packages): Add complex-spaces package
  packages/complex-spaces.lua
Labels: enhancement

#1156 Fix UTF8 conversion utility functions
  core/utilities.lua
  spec/utilities_spec.lua
Labels: bug
