Repository sile-typesetter/sile, pull requests merged in 2022-12, with the labels that each got.

#1563 Fixup developer tooling so manual is easier to build
  .cirrus.yml
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  Makefile-fonts
  Makefile.am
  README.md
  build-aux/ax_font.m4
  configure.ac
  documentation/c02-gettingstarted.sil
  flake.nix
  tests/regressions.pl.in
Labels: todo, builds & releases

#1623 +§ Installing third-party packages
  README.md
  documentation/c02-gettingstarted.sil
Labels: documentation

#1640 Deprecate \listitem and \quote
  classes/plain.lua
Labels: todo

#1639 Add interface for packages to load packages
  packages/autodoc/init.lua
  packages/background/init.lua
  packages/base.lua
  packages/chapterverse/init.lua
  packages/chordmode/init.lua
  packages/cropmarks/init.lua
  packages/dropcaps/init.lua
  packages/folio/init.lua
  packages/footnotes/init.lua
  packages/frametricks/init.lua
  packages/hanmenkyoshi/init.lua
  packages/lists/init.lua
  packages/pandoc/init.lua
  packages/pdfstructure/init.lua
  packages/pullquote/init.lua
  packages/ruby/init.lua
  packages/rules/init.lua
  packages/tableofcontents/init.lua
  packages/tate/init.lua
  packages/textcase/init.lua
  packages/url/init.lua
Labels: todo

#1646 Bump dependencies to latest upstream
  package.json
  sile-dev-1.rockspec
Labels: todo

#1645 Cleanup default module search paths, improve error messages
  core/sile.lua
  outputters/debug.lua
  sile.in
Labels: bug

#1638 Cleanup inputter AST nesting expectations
  documentation/c02-gettingstarted.sil
  inputters/base.lua
  inputters/sil.lua
  inputters/sil_spec.lua
  inputters/xml.lua
  inputters/xml_spec.lua
  packages/autodoc/init.lua
  packages/chordmode/init.lua
  packages/inputfilter/init.lua
  packages/url/init.lua
Labels: todo

#1643 Add CI workflow to get some code coverage back
  .github/workflows/coverage.yml
  Makefile.am
  build-aux/list-dist-files.sh.in
  configure.ac
  core/utilities.lua
  inputters/lua.lua
  tests/049EPH.xml
  tests/balanced.sil
  tests/bug-214.sil
  tests/bug-248.sil
  tests/bug-307.sil
  tests/bug-342.sil
  tests/color-fonts.sil
  tests/footnotes-twocols.sil
  tests/frametricks.sil
  tests/process-commands.sil
  tests/space-after-command.sil
  tests/sura-2.sil
Labels: todo, ci

#1652 Correct filename in debug info after includes
  core/sile.lua
Labels: bug

#1655 bibtex package: Fix \cite{key}
  packages/bibtex/init.lua
Labels: bug

#1651 Refactor typesetters as independent module and fix grid bugs
  .commitlintrc.yml
  build-aux/list-dist-files.sh.in
  classes/base.lua
  classes/tplain.lua
  core/pagebuilder.lua
  core/sile.lua
  packages/balanced-frames/init.lua
  packages/bidi/init.lua
  packages/break-firstfit/init.lua
  packages/font-fallback/init.lua
  packages/grid/init.lua
  packages/insertions/init.lua
  packages/linespacing/init.lua
  packages/parallel/init.lua
  packages/tate/init.lua
  pagebuilders/base.lua
  pagebuilders/grid.lua
  shapers/fallback.lua
  spec/break_spec.lua
  spec/utilities_spec.lua
  tests/bidi.expected
  tests/bug-1430.expected
  tests/bug-1430.sil
  tests/bug-244.expected
  typesetters/base.lua
  typesetters/firstfit.lua
  typesetters/grid.lua
  typesetters/tate.lua
Labels: bug

#1662 fix(shaper): Respect variations when shaping (#1265)
  src/justenoughharfbuzz.c
Labels: bug

#1656 Bring LuaJIT support up to 100% parity
  core/utilities.lua
  tests/bug-1069.expected
  tests/bug-1069.sil
Labels: builds & releases

#1666 Correct font-variants using opsz axis
  src/justenoughharfbuzz.c
Labels: bug

#1671 Patch up error message when failing to load font
  outputters/libtexpdf.lua
Labels: bug

#1669 Fixup build time issues
  .github/workflows/nix.yml
  Makefile-fonts
  build-aux/ax_font.m4
  configure.ac
  flake.nix
Labels: builds & releases

#1675 Shim legacy function and over haul documentation re typesetters
  core/deprecations.lua
  documentation/c12-tricks.sil
Labels: todo

#1676 Redo SIL inputter to fix regression, re-allow fragments
  inputters/sil.lua
  inputters/sil_spec.lua
  tests/bug-1674.expected
  tests/bug-1674.sil
Labels: bug
