Repository sile-typesetter/sile, pull requests merged in 2022-06, with the labels that each got.

#1414 Move special callbacks in TOC package out of class into package
  classes/base.lua
  classes/bible.lua
  classes/book.lua
  classes/docbook.lua
  classes/plain.lua
  core/utilities.lua
  documentation/c10-classdesign.sil
  documentation/c11-xmlproc.sil
  documentation/sile.sil
  languages/ja.lua
  packages/autodoc.lua
  packages/bibtex/bibliography.lua
  packages/bibtex/init.lua
  packages/bibtex/styles/chicago.lua
  packages/boustrophedon.lua
  packages/chapterverse.lua
  packages/chordmode.lua
  packages/color-fonts.lua
  packages/color.lua
  packages/complex-spaces.lua
  packages/converters.lua
  packages/counters.lua
  packages/cropmarks.lua
  packages/date.lua
  packages/debug.lua
  packages/features.lua
  packages/folio.lua
  packages/font-fallback.lua
  packages/footnotes.lua
  packages/frametricks.lua
  packages/grid.lua
  packages/gutenberg.lua
  packages/hanmenkyoshi.lua
  packages/ifattop.lua
  packages/image.lua
  packages/indexer.lua
  packages/infonode.lua
  packages/inputfilter.lua
  packages/leaders.lua
  packages/linespacing.lua
  packages/lorem.lua
  packages/math/base-elements.lua
  packages/math/init.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
  packages/pdf.lua
  packages/pdfstructure.lua
  packages/raiselower.lua
  packages/rebox.lua
  packages/simpletable.lua
  packages/svg/init.lua
  packages/tableofcontents.lua
  packages/twoside.lua
  packages/unichar.lua
  packages/url.lua
  packages/xmltricks.lua
Labels: todo

#1415 Minor cleanup to class code, catch some init stuff not in classes not covered by tests
  classes/bible.lua
  classes/diglot.lua
  classes/docbook.lua
  classes/pecha.lua
  classes/plain.lua
  classes/triglot.lua
  documentation/c12-tricks.sil
Labels: todo

#1412 Bump dev tools, get Nix working
  .github/workflows/nix.yml
  flake.lock
  flake.nix
  package.json
Labels: todo, builds & releases

#1419 Touchup nix flake usage
  README.md
  documentation/c02-gettingstarted.sil
  flake.lock
  flake.nix
Labels: todo, documentation, builds & releases

#1422 feat: Add strikethrough command to the rules package
  core/opentype-parser.lua
  packages/rules.lua
Labels: enhancement

#1421 Post-release cleanup
  README.md
  classes/book.lua
  core/cairo-output.lua
  core/debug-output.lua
  core/length.lua
  core/libtexpdf-output.lua
  core/measurement.lua
  core/podofo-output.lua
  core/text-output.lua
  core/typesetter.lua
  documentation/c02-gettingstarted.sil
  flake.nix
  packages/folio.lua
  packages/gutenberg.lua
  packages/pdf.lua
  packages/rules.lua
  packages/svg/init.lua
  packages/tableofcontents.lua
  sile-dev-1.rockspec
  sile.in
Labels: todo

#1424 Update CI runner environments
  .github/workflows/build.yml
  .github/workflows/commitlint.yml
  .github/workflows/deploy.yml
  .github/workflows/luacheck.yml
  .github/workflows/nix.yml
  .github/workflows/test.yml
  .github/workflows/versioning.yml
  README.md
  documentation/c02-gettingstarted.sil
Labels: ci, builds & releases

#1425 Add hrulefill command and redo fullrule so as not to overflow lines
  packages/rules.lua
  tests/feat-fullrule-hfillrule.expected
  tests/feat-fullrule-hfillrule.sil
Labels: bug, enhancement

#1429 Make leaders explicit non-discardable glues
  packages/leaders.lua
  tests/feat-875-leaders-alignment.expected
  tests/feat-875-leaders-alignment.sil
Labels: bug

#1437 Update documentation
  README.md
  documentation/c02-gettingstarted.sil
  documentation/c09-concepts.sil
  documentation/sile.sil
Labels: documentation

#1445 fix(build): Make sure `i18n/` dir is actually distributed
  build-aux/list-dist-files.sh
Labels: bug, builds & releases

#1365 Lightweight enumerations and bullet lists
  documentation/c04-useful.sil
  documentation/c05-packages.sil
  documentation/c07-settings.sil
  documentation/c09-concepts.sil
  documentation/c10-classdesign.sil
  documentation/c12-tricks.sil
  documentation/macros.sil
  documentation/sile.sil
  packages/chapterverse/init.lua
  packages/counters/init.lua
  packages/folio/init.lua
  packages/grid/init.lua
  packages/lists/init.lua
  packages/pullquote/init.lua
  packages/tableofcontents/init.lua
  tests/feat-1365-lists-alternate.expected
  tests/feat-1365-lists-alternate.sil
  tests/feat-1365-lists-compact.expected
  tests/feat-1365-lists-compact.sil
  tests/feat-1365-lists-footnote.expected
  tests/feat-1365-lists-footnote.sil
Labels: enhancement, packages

#1447 fix(core): Move the zenkaku width (全角幅; `zw`) unit into core
  core/settings.lua
  core/units.lua
  languages/ja.lua
  packages/ruby/init.lua
Labels: bug, enhancement

#1451 Fixup zw unit and general error handling
  core/units.lua
  core/utilities.lua
  documentation/c05-packages.sil
  documentation/c08-language.sil
  packages/font-fallback/init.lua
  packages/lists/init.lua
  packages/ruby/init.lua
Labels: bug

#1444 feat(languages): Add full Esperanto language support
  documentation/c08-language.sil
  i18n/eo.ftl
  languages/eo.lua
  spec/utilities_spec.lua
Labels: enhancement

#1456 fix(classes): Clarify the scopes of `tate` and `jplain`
  classes/jbook.lua
  classes/jplain.lua
  classes/tbook.lua
  classes/tplain.lua
  documentation/c08-language.sil
  tests/bug-1101.sil
  tests/bug-1171.expected
  tests/bug-244.sil
  tests/bug-524.sil
  tests/bug-525.sil
  tests/bug-915.sil
  tests/bug-926.sil
  tests/jbook.expected
  tests/vertical.sil
Labels: bug, classes

#1460 Fixup TOC / PDF link package idempotency
  packages/background/init.lua
  packages/bibtex/init.lua
  packages/boustrophedon/init.lua
  packages/chapterverse/init.lua
  packages/cropmarks/init.lua
  packages/date/init.lua
  packages/features/init.lua
  packages/gutenberg/init.lua
  packages/specimen/init.lua
  packages/svg/init.lua
  packages/tableofcontents/init.lua
Labels: bug, documentation

#1443 Cleanup font fallback handling
  core/font.lua
  core/harfbuzz-shaper.lua
  packages/font-fallback/init.lua
  tests/bug-1442-fallback-font-options.expected
  tests/bug-1442-fallback-font-options.sil
  tests/font-fallback-empty.expected
  tests/font-fallback-empty.sil
Labels: bug, enhancement

#1420 Drop v0.13 era temporary provides and shims
  .cirrus.yml
  classes/base.lua
  classes/bible.lua
  classes/book.lua
  classes/diglot.lua
  classes/docbook.lua
  classes/jbook.lua
  classes/jplain.lua
  classes/letter.lua
  classes/markdown.lua
  classes/plain.lua
  classes/triglot.lua
  configure.ac
  core/inputs-common.lua
  core/nodefactory.lua
  core/settings.lua
  core/sile.lua
  flake.lock
  flake.nix
  packages/counters/init.lua
  packages/date/init.lua
  packages/folio/init.lua
  packages/gutenberg/init.lua
  packages/infonode/init.lua
  packages/masters/init.lua
  packages/tableofcontents/init.lua
  packages/twoside/init.lua
  sile-dev-1.rockspec
  spec/complex_frame_spec.lua
Labels: todo

#1450 Enable Luarocks to install SILE packages
  .github/workflows/build.yml
  .github/workflows/test.yml
  Makefile.am
  core/inputs-common.lua
  core/makedeps.lua
  core/packagemanager.lua
  documentation/c05-packages.sil
  sile.in
  src/Makefile.am
Labels: todo
