Repository sile-typesetter/sile, pull requests merged in 2022-09, with the labels that each got.

#1549 Fixup unicode output in unichar section of manual
  packages/unichar/init.lua
Labels: documentation

#1550 Make sure PDF initialized before PDF package does anything
  packages/pdf/init.lua
  packages/pdfstructure/init.lua
Labels: bug

#1553 docs(manual): Improve some bullet lists and apostrophes
  documentation/c02-gettingstarted.sil
  documentation/c05-packages.sil
  documentation/c08-language.sil
  documentation/c10-classdesign.sil
  documentation/c11-xmlproc.sil
  documentation/developers.sil
Labels: documentation

#1554 Only combine unichar'ed chars with same font
  packages/unichar/init.lua
  tests/bug-991-unichar.expected
  tests/bug-991-unichar.sil
Labels: bug

#1555 docs(manual): Mention `\strong` command as shorcut for weight 700
  documentation/c04-useful.sil
Labels: documentation

#1561 Somewhat Refactor the Build documentation
  README.md
  documentation/c02-gettingstarted.sil
Labels: documentation

#1541 Rework simple and multilevel counters
  packages/counters/counters_spec.lua
  packages/counters/init.lua
  tests/bug-522.expected
  tests/mlcounter.expected
Labels: packages

#1571 Code typos in 0.14
  core/sile.lua
  packages/textcase/init.lua
Labels: bug

#1573 fix(math): Fix insertion order of MathML children
  packages/math/texlike.lua
Labels: bug

#1574 Add developer setup for LSP enabled editors
  .editorconfig
  .luarc.json
  core/deprecations.lua
  inputters/sil.lua
  packages/bibtex/bibliography.lua
  packages/bibtex/init.lua
  packages/bibtex/styles/chicago.lua
  packages/math/texlike.lua
Labels: todo

#1564 Fix regression and further improve rotation package
  packages/rotate/init.lua
Labels: bug
