Repository sile-typesetter/sile, pull requests merged in 2022-04, with the labels that each got.

#1348 dotfill stretch (#1343) and leaders vertical alignment (#875)
  packages/leaders.lua
  tests/bug-1343-dotfill-stretch.expected
  tests/bug-1343-dotfill-stretch.sil
  tests/bug-243.expected
  tests/bug-243.sil
  tests/bug-859.expected
  tests/feat-875-dotfill-alignment.expected
  tests/feat-875-dotfill-alignment.sil
  tests/feat-875-leaders-alignment.expected
  tests/feat-875-leaders-alignment.sil
  tests/feat-875-leaders-fixed-alignment.expected
  tests/feat-875-leaders-fixed-alignment.sil
Labels: bug, enhancement

#1357 fix(deps): Correct include to work with current LuaRocks packages
  lua-libraries/lunamark/entities.lua
  lua-libraries/lunamark/reader/markdown.lua
Labels: bug

#1363 Fix up CI builds and Lua versions situation
  .cirrus.yml
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: todo

#1360 French punctuation spacing must honor current font size
  languages/fr.lua
  tests/bug-1359.expected
  tests/bug-1359.sil
Labels: bug

#1342 Leverage package documentation and manual (stage 1)
  packages/autodoc.lua
  packages/background.lua
  packages/balanced-frames.lua
  packages/bibliography.lua
  packages/bibtex.lua
  packages/bidi.lua
  packages/boustrophedon.lua
  packages/chapterverse.lua
  packages/chordmode.lua
  packages/color-fonts.lua
  packages/color.lua
  packages/converters.lua
  packages/counters.lua
  packages/cropmarks.lua
  packages/date.lua
  packages/debug.lua
  packages/dropcaps.lua
  packages/features.lua
  packages/folio.lua
  packages/font-fallback.lua
  packages/footnotes.lua
  packages/frametricks.lua
  packages/grid.lua
  packages/gutenberg.lua
  packages/hanmenkyoshi.lua
  packages/ifattop.lua
  packages/image.lua
  packages/indexer.lua
  packages/infonode.lua
  packages/inputfilter.lua
  packages/insertions.lua
  packages/leaders.lua
  packages/linespacing.lua
  packages/lorem.lua
  packages/masters.lua
  packages/math.lua
  packages/parallel.lua
  packages/pdf.lua
  packages/pdfstructure.lua
  packages/pullquote.lua
  packages/raiselower.lua
  packages/rebox.lua
  packages/rotate.lua
  packages/ruby.lua
  packages/rules.lua
  packages/simpletable.lua
  packages/specimen.lua
  packages/svg.lua
  packages/tableofcontents.lua
  packages/tate.lua
  packages/textcase.lua
  packages/twoside.lua
  packages/unichar.lua
  packages/url.lua
  packages/verbatim.lua
  packages/xmltricks.lua
Labels: documentation

#1354 Keep configure and install BSD and POSIX friendly
  Makefile.am
  configure.ac
Labels: bug

#675 Leverage Fluent and Unicode CLDR for localization
  .cirrus.yml
  .gitattributes
  classes/book.lua
  configure.ac
  core/font.lua
  core/inputs-texlike.lua
  core/languages.lua
  core/settings.lua
  core/sile.lua
  core/utilities.lua
  documentation/c08-language.sil
  i18n/cs.ftl
  i18n/en.ftl
  i18n/ja.ftl
  i18n/tr.ftl
  i18n/und.ftl
  languages/cs.lua
  languages/en.lua
  languages/ja.lua
  languages/tr.lua
  packages/bibliography.lua
  packages/tableofcontents.lua
  sile-dev-1.rockspec
  tests/bug-990.expected
  tests/bug-990.sil
  tests/fluent.expected
  tests/fluent.sil
Labels: enhancement

#1372 Tooling dependency bumps
  package.json
  sile-dev-1.rockspec
Labels: todo

#1380 Drop std.string.monkey_patch()
  core/debug-output.lua
  core/font.lua
  core/frame.lua
  core/harfbuzz-shaper.lua
  core/makedeps.lua
  core/measurement.lua
  core/nodefactory.lua
  core/opentype-parser.lua
  core/packagemanager.lua
  core/typesetter.lua
  core/utilities.lua
  languages/ja.lua
  languages/unicode.lua
  packages/autodoc.lua
  packages/bidi.lua
  packages/break-firstfit.lua
  packages/chapterverse.lua
  packages/features.lua
  packages/font-fallback.lua
  packages/grid.lua
  packages/insertions.lua
  packages/math/base-elements.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
  packages/parallel.lua
  packages/pdfstructure.lua
  packages/ruby.lua
  sile-dev-1.rockspec
Labels: todo

#1383 An hrule with a depth shall not affect current baseline
  packages/rules.lua
  tests/percent-units.expected
Labels: bug
