Repository sile-typesetter/sile, pull requests merged in 2022-08, with the labels that each got.

#1496 math: Modulus support, operator atom type override, space commands, and macro fix
  packages/math/base-elements.lua
  packages/math/init.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
  packages/math/unicode-symbols.lua
  tests/math-bigops.expected
  tests/math-bigops.xml
  tests/math-fractions.expected
  tests/math-macros.expected
  tests/math-ops.expected
  tests/math-ops.sil
  tests/math-spaces.expected
  tests/math-spaces.sil
  tests/math-subsup.expected
  tests/math-tables-mathml.expected
  tests/math-tables-tex.expected
  tests/math-variants.expected
  tests/math-variants.xml
Labels: bug, enhancement

#1499 Pass document direction info to font shaper by default
  classes/plain.lua
  packages/bidi/init.lua
Labels: bug

#1501 Minor href regression and grid fix
  packages/grid/init.lua
  packages/url/init.lua
Labels: bug

#1506 Parse height argument to in raiselower package as measurement
  packages/raiselower/init.lua
Labels: bug

#1514 Cleanup internal use of immanently deprecated APIs
  classes/base.lua
  classes/docbook.lua
  core/deprecations.lua
  core/sile.lua
  inputters/base.lua
  packages/autodoc/init.lua
  packages/balanced-frames/init.lua
  packages/base.lua
  packages/footnotes/init.lua
  packages/linespacing/init.lua
  packages/math/init.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
Labels: todo

#1516 Last minute touchups
  core/cli.lua
  core/utilities.lua
  inputters/base.lua
  sile.in
Labels: todo

#1518 Bring postambles to parity with preambles
  inputters/base.lua
Labels: enhancement

#1522 Touchup package annoyances
  classes/base.lua
  classes/book.lua
  core/measurement.lua
  packages/base.lua
  packages/math/init.lua
  packages/parallel/init.lua
  packages/tableofcontents/init.lua
  sile.in
Labels: bug

#1527 Discretionary glyphs vs. hyphenation
  core/break.lua
  core/hyphenator-liang.lua
  core/nodefactory.lua
  languages/tr.lua
  tests/bug-269.expected
  tests/bug-283.expected
  tests/bug-283.sil
  tests/bug-355-tr-hyphenation.expected
  tests/bug-355-tr-hyphenation.sil
  tests/hyph-except.expected
  tests/hyph-except.sil
  typesetters/base.lua
Labels: bug

#1500 Image resolution and PDF page selection with libtexpdf backend
  documentation/c12-tricks.sil
  outputters/debug.lua
  outputters/libtexpdf.lua
  packages/image/init.lua
  src/imagebbox.c
  src/justenoughlibtexpdf.c
Labels: enhancement

#1529 Add API so packages know their basedir and can load relative assets
  packages/base.lua
Labels: enhancement, packages

#1537 Move tableofcontents loading to package method
  packages/tableofcontents/init.lua
Labels: todo

#1540 fix(justenoughlibtexpdf): pdf_metadata
  src/justenoughlibtexpdf.c
Labels: bug, builds & releases

#1546 docs(readme): `a a`→`a`
  README.md
Labels: documentation

#1542 Avoid mktemp during build, breaks opensuse packaging
  Makefile.am
Labels: builds & releases

#1535 Fix issues with --options and --class
  core/cli.lua
  inputters/base.lua
Labels: bug
