Repository sile-typesetter/sile, pull requests merged in 2022-03, with the labels that each got.

#1335 Leverage package documentation and manual (stage 0)
  documentation/c03-input.sil
  documentation/c04-useful.sil
  documentation/c05-packages.sil
  documentation/c07-settings.sil
  documentation/c08-language.sil
  documentation/c09-concepts.sil
  documentation/macros.sil
  documentation/sile.sil
  packages/autodoc.lua
  packages/chordmode.lua
  packages/color.lua
  packages/dropcaps.lua
  packages/image.lua
  packages/linespacing.lua
  packages/math.lua
  packages/url.lua
Labels: documentation

#1341 Fix issues raised by LuaHelper
  packages/bibliography.lua
  packages/tate.lua
Labels: todo

#1345 Update and cleanup repo tooling
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/luacheck.yml
  .github/workflows/test.yml
  .luacheckrc
  Dockerfile
  Makefile.am
  core/baseclass.lua
  core/frame.lua
  core/opentype-parser.lua
  core/utilities.lua
  hooks/build
  package.json
  sile-dev-1.rockspec
Labels: todo, builds & releases
