Repository sile-typesetter/sile, pull requests merged in 2022-05, with the labels that each got.

#1065 Refactor document classes using Penlight model
  classes/base.lua
  classes/bible.lua
  classes/book.lua
  classes/diglot.lua
  classes/docbook.lua
  classes/jbook.lua
  classes/jplain.lua
  classes/letter.lua
  classes/markdown.lua
  classes/pecha.lua
  classes/plain.lua
  classes/triglot.lua
  core/baseclass.lua
  core/classes.lua
  core/frame.lua
  core/harfbuzz-shaper.lua
  core/inputs-common.lua
  core/nodefactory.lua
  core/pango-shaper.lua
  core/sile.lua
  core/tracestack.lua
  documentation/c10-classdesign.sil
  documentation/c12-tricks.sil
  languages/am.lua
  languages/fr.lua
  languages/ja.lua
  languages/jv.lua
  languages/tr.lua
  languages/unicode.lua
  packages/boustrophedon.lua
  packages/color-fonts.lua
  packages/folio.lua
  packages/font-fallback.lua
  packages/grid.lua
  packages/infonode.lua
  packages/insertions.lua
  packages/leaders.lua
  packages/masters.lua
  packages/parallel.lua
  packages/rules.lua
  packages/tate.lua
  spec/complex_frame_spec.lua
  tests/classes/testsidenote.lua
  tests/classes/testtwocol.lua
  tests/footnotes-twocols.sil
  tests/letter.sil
Labels: todo

#1387 Fix bringhurst example in docs
  documentation/c10-classdesign.sil
Labels: documentation

#1389 Poke at Nix and BSD build stuff
  Makefile.am
  flake.lock
  sile-dev-1.rockspec
Labels: todo, builds & releases

#1392 Refactor typesetter, removed last usage of Lua stdlib
  classes/base.lua
  classes/jbook.lua
  classes/jplain.lua
  core/font.lua
  core/frame.lua
  core/inputs-common.lua
  core/sile.lua
  core/typesetter.lua
  packages/autodoc.lua
  packages/balanced-frames.lua
  packages/bibliography.lua
  packages/bibstyles/chicago.lua
  packages/bidi.lua
  packages/footnotes.lua
  packages/insertions.lua
  packages/linespacing.lua
  packages/math/base-elements.lua
  packages/pagebuilder-bestfit.lua
  packages/parallel.lua
  packages/rotate.lua
  packages/tate.lua
  spec/break_spec.lua
  spec/complex_frame_spec.lua
Labels: todo

#1395 Address warnings on bootstrap
  configure.ac
Labels: todo, builds & releases

#1378 Properly justify lines containing ligatures (workaround)
  core/typesetter.lua
  tests/bug-1362.expected
  tests/bug-1362.sil
  tests/bug-283.expected
  tests/bug-79.expected
Labels: bug

#1401 Always output pdf on finish() even if no content
  core/libtexpdf-output.lua
Labels: bug

#1405 More followup refactoring after class changes
  classes/base.lua
  classes/bible.lua
  classes/book.lua
  core/sile.lua
  core/typesetter.lua
  documentation/c10-classdesign.sil
  packages/footnotes.lua
  packages/insertions.lua
  packages/masters.lua
  packages/twoside.lua
Labels: todo

#1408 More followup on class refactoring
  classes/base.lua
  classes/bible.lua
  classes/book.lua
  classes/diglot.lua
  classes/docbook.lua
  classes/jbook.lua
  classes/jplain.lua
  classes/letter.lua
  classes/markdown.lua
  classes/pecha.lua
  classes/plain.lua
  classes/triglot.lua
  core/inputs-common.lua
  documentation/c10-classdesign.sil
  documentation/c12-tricks.sil
  packages/pandoc.lua
  spec/complex_frame_spec.lua
  tests/classes/testsidenote.lua
  tests/classes/testtwocol.lua
Labels: todo

#1410 Cleanup language function deprecations related to Fluent
  classes/book.lua
  packages/tableofcontents.lua
Labels: todo
