Repository sile-typesetter/sile, pull requests merged in 2022-07, with the labels that each got.

#1467 Add Norwegian localizations and cleanup warning messages
  core/languages.lua
  i18n/no.ftl
Labels: enhancement

#1468 Add Norwegian localization variants
  Makefile.am
  i18n/nb.ftl
  i18n/nn.ftl
  languages/nb.lua
  languages/nn.lua
  languages/no.lua
  spec/languages_spec.lua
Labels: enhancement

#1479 Make \script command properly initialize packages
  classes/base.lua
Labels: bug

#1347 Add inline-escaping in SIL-language
  classes/base.lua
  core/sile.lua
  inputters/sil.lua
  packages/svg/init.lua
  tests/feat-1092-raw.expected
  tests/feat-1092-raw.sil
Labels: enhancement

#1473 Stricter color parsing and improved color package documentation
  core/color.lua
  core/color_spec.lua
  core/colorparser.lua
  core/deprecations.lua
  core/sile.lua
  packages/background/init.lua
  packages/color/init.lua
  packages/pdf/init.lua
Labels: enhancement

#1483 Rewrite DocBook example in manual
  classes/base.lua
  classes/docbook.lua
  classes/docbook.sil
  documentation/c11-xmlproc.sil
  inputters/base.lua
  inputters/xml.lua
  inputters/xml_spec.lua
Labels: documentation

#1488 chore(deps): Bump Lua Penlight dependency to latest release
  sile-dev-1.rockspec
Labels: builds & releases

#1490 Fix minor typos in the SILE book
  documentation/c02-gettingstarted.sil
  documentation/c03-input.sil
  documentation/c04-useful.sil
  documentation/c05-packages.sil
  documentation/c06-macroscommands.sil
  documentation/c07-settings.sil
  documentation/c08-language.sil
  documentation/c09-concepts.sil
  documentation/c10-classdesign.sil
  documentation/c11-xmlproc.sil
  documentation/c12-tricks.sil
Labels: documentation

#1497 Setup and use cleaner API for package exports
  classes/book.lua
  core/sile.lua
  core/tracestack.lua
  packages/autodoc/init.lua
  packages/base.lua
  packages/bidi/init.lua
  packages/break-firstfit/init.lua
  packages/chordmode/init.lua
  packages/converters/init.lua
  packages/counters/init.lua
  packages/date/init.lua
  packages/folio/init.lua
  packages/frametricks/init.lua
  packages/hanmenkyoshi/init.lua
  packages/indexer/init.lua
  packages/infonode/init.lua
  packages/inputfilter/init.lua
  packages/insertions/init.lua
  packages/masters/init.lua
  packages/tableofcontents/init.lua
  packages/textcase/init.lua
  packages/twoside/init.lua
  packages/url/init.lua
Labels: enhancement, packages
