Repository sile-typesetter/sile, pull requests merged in 2022-01, with the labels that each got.

#1302 Allow build to be reproducible
  build-aux/ax_build_date_epoch.m4
  configure.ac
Labels: todo

#1306 Bump dependencies
  package.json
  sile-dev-1.rockspec
Labels: todo

#1264 feat(core): Implement paragraph shaping (parshape)
  core/break.lua
  core/typesetter.lua
  libtexpdf.git-rev
  tests/parshaping-simple.expected
  tests/parshaping-simple.sil
Labels: enhancement

#1307 Document typesetter changes
  documentation/c01-whatis.sil
  documentation/c07-settings.sil
  documentation/c09-concepts.sil
Labels: documentation

#1308 Fix regression of #579
  Makefile-fonts
  core/base-shaper.lua
  spec/shaper_spec.lua
  tests/negative-spaces-in-line.expected
  tests/negative-spaces-in-line.sil
Labels: bug
