Repository sile-typesetter/sile, pull requests merged in 2022-11, with the labels that each got.

#1582 s/--deps-only/--only-deps/
  README.md
  documentation/c02-gettingstarted.sil
Labels: documentation

#1583 path to sile + same only-deps change from other PR
  documentation/c02-gettingstarted.sil
  documentation/c07-settings.sil
Labels: documentation

#1584 Paper size present documentation
  documentation/c03-input.sil
Labels: documentation

#1585 Remove misleading text about latin hyphenation
  core/font.lua
  documentation/c03-input.sil
  languages/und.lua
Labels: bug

#1589 Fix inline→block mode swith at chapter starts
  classes/book.lua
  documentation/c05-packages.sil
  documentation/c08-language.sil
  documentation/c10-classdesign.sil
  documentation/c11-xmlproc.sil
  documentation/developers.sil
  documentation/sile.sil
Labels: bug

#1591 Fixup folios in manual
  documentation/c01-whatis.sil
  documentation/sile.sil
Labels: documentation

#1592 Fix masters package master switch inhibiting page breaks
  packages/masters/init.lua
  tests/bug-1580.expected
  tests/bug-1580.sil
Labels: bug

#1594 Revive FreeBSD 13.0 CI runner
  .cirrus.yml
Labels: ci

#1596 Permit content outside of the document note, e.g. comments or blanks
  inputters/base.lua
Labels: bug

#1608 Allow redefinition of existing units
  core/sile.lua
Labels: bug

#1612 Don't count some passthrough tags twice in the AST
  inputters/sil.lua
  tests/bug-1611.expected
  tests/bug-1611.sil
  typesetters/base.lua
Labels: bug

#1613 Test relaxed (and further fix) content type sniffing rules
  inputters/lua.lua
  inputters/sil.lua
  tests/bug-502.expected
  tests/bug-502.sil
Labels: bug

#1615 fix(packages): Ensure a page switch does not break boustrophedon
  packages/boustrophedon/init.lua
Labels: bug, packages

#1618 Improved line breaks in the SILE Manual
  documentation/c07-settings.sil
  documentation/sile.sil
Labels: documentation

#1633 Small typo in Esperanto language section
  documentation/c08-language.sil
Labels: documentation

#1634 Fix debug functions that still assume luastd
  core/pagebuilder.lua
  typesetters/base.lua
Labels: bug

#1627 Pagebreak and friends
  classes/plain.lua
  documentation/c04-useful.sil
  tests/bug-262.expected
  tests/masters.sil
  typesetters/base.lua
Labels: bug

#1632 Number formatting for many languages and sorting (collation) with ICU
  core/utilities-numbers.lua
  core/utilities-sorting.lua
  core/utilities.lua
  languages/en.lua
  languages/eo.lua
  languages/tr.lua
  packages/counters/init.lua
  spec/utilities_spec.lua
  src/justenoughicu.c
  tests/counters.expected
  tests/counters.sil
Labels: enhancement

#1629 Document how to install for Fedora
  README.md
  documentation/c02-gettingstarted.sil
Labels: documentation

#1620 Better code blocks in SILE manual and package docs
  documentation/c02-gettingstarted.sil
  documentation/c03-input.sil
  documentation/c04-useful.sil
  documentation/c05-packages.sil
  documentation/c06-macroscommands.sil
  documentation/c07-settings.sil
  documentation/c08-language.sil
  documentation/c09-concepts.sil
  documentation/c10-classdesign.sil
  documentation/c11-xmlproc.sil
  documentation/c12-tricks.sil
  documentation/macros.sil
  packages/autodoc/init.lua
  packages/chordmode/init.lua
  packages/converters/init.lua
  packages/counters/init.lua
  packages/features/init.lua
  packages/folio/init.lua
  packages/font-fallback/init.lua
  packages/frametricks/init.lua
  packages/infonode/init.lua
  packages/leaders/init.lua
  packages/math/init.lua
  packages/raiselower/init.lua
  packages/rebox/init.lua
  packages/rotate/init.lua
  packages/ruby/init.lua
  packages/rules/init.lua
  packages/simpletable/init.lua
  packages/specimen/init.lua
  packages/unichar/init.lua
  packages/verbatim/init.lua
Labels: documentation

#1636 Overhaul debug calls for speed & robustness
  classes/base.lua
  classes/plain.lua
  core/break.lua
  core/font.lua
  core/frame.lua
  core/opentype-parser.lua
  core/pagebuilder.lua
  core/sile.lua
  core/tracestack.lua
  core/utilities.lua
  languages/ug.lua
  languages/unicode.lua
  packages/balanced-frames/init.lua
  packages/break-firstfit/init.lua
  packages/chapterverse/init.lua
  packages/converters/init.lua
  packages/font-fallback/init.lua
  packages/grid/init.lua
  packages/insertions/init.lua
  packages/leaders/init.lua
  packages/math/base-elements.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
  packages/pandoc/init.lua
  packages/parallel/init.lua
  packages/ruby/init.lua
  shapers/harfbuzz.lua
  typesetters/base.lua
Labels: todo
