Repository sile-typesetter/sile, pull requests merged in 2023-10, with the labels that each got.

#1871 fix(tooling): Fix Nix buld for rustier sile
  .envrc
  .gitignore
  Makefile.am
  build-aux/pkg.nix
  flake.lock
  flake.nix
  package.json
Labels: builds & releases

#1881 docs(readme): Remove unreachable closed japanese google group
  README.md
Labels: documentation

#1885 Spellcheck the manual plus some source code stuff
  README.md
  classes/docbook.lua
  classes/plain.lua
  classes/tplain.lua
  core/break.lua
  core/nodefactory.lua
  core/sile.lua
  core/utilities-numbers.lua
  core/utilities.lua
  documentation/c02-gettingstarted.sil
  documentation/c03-input.sil
  documentation/c05-packages.sil
  documentation/c06-macroscommands.sil
  documentation/c08-language.sil
  documentation/c10-classdesign.sil
  documentation/c11-inputoutput.sil
  documentation/c12-xmlproc.sil
  inputters/base.lua
  outputters/debug.lua
  outputters/libtexpdf.lua
  packages/autodoc/init.lua
  packages/leaders/init.lua
  packages/lists/init.lua
  packages/math/base-elements.lua
  packages/ruby/init.lua
  packages/simpletable/init.lua
  src/justenoughicu.c
  tests/vertical.sil
  typesetters/base.lua
Labels: todo

#1887 Get Lua 5.1 CI working again
  .github/workflows/test.yml
  Makefile-luarocks
  Makefile.am
  packages/footnotes/init.lua
  src/justenoughharfbuzz.c
Labels: bug, ci

#1888 Silence resolveFile()
  core/sile.lua
  packages/bibtex/init.lua
Labels: todo

#1902 Backport a couple things from develop to master
  configure.ac
  sile.in
Labels: enhancement

#1901 Fix on command makecolumns
  packages/frametricks/init.lua
  tests/makecolumns.expected
  tests/makecolumns.sil
Labels: bug
