Repository sile-typesetter/sile, pull requests merged in 2023-12, with the labels that each got.

#1924 Fix linter to be stricter 5.1
  .luacheckrc
  core/cli.lua
  core/deprecations.lua
  core/packagemanager.lua
  core/sile.lua
  core/utilities.lua
  outputters/debug.lua
  outputters/text.lua
  packages/base.lua
  packages/bibtex/bibliography.lua
  packages/math/base-elements.lua
  packages/math/texlike.lua
Labels: todo

#1914 Refactor AST utilities
  classes/base.lua
  classes/book.lua
  core/font.lua
  core/languages.lua
  core/utilities/ast.lua
  core/utilities/init.lua
  core/utilities/numbers.lua
  core/utilities/sorting.lua
  documentation/c10-classdesign.sil
  documentation/c12-xmlproc.sil
  inputters/base.lua
  inputters/xml.lua
  packages/autodoc/init.lua
  packages/bibtex/init.lua
  packages/inputfilter/init.lua
  packages/tableofcontents/init.lua
  typesetters/base.lua
Labels: enhancement

#1935 Feat unicode softhyphen support
  documentation/c08-language.sil
  tests/feat-unicode-softhyphen.expected
  tests/feat-unicode-softhyphen.sil
  typesetters/base.lua
Labels: enhancement

#1929 Change module load error to include suggestions of how to install 3rd party modules
  core/sile.lua
  core/utilities.lua
  sile.in
Labels: enhancement

#1918 Native unicode U+00A0 (nbsp) support
  documentation/c07-settings.sil
  languages/fr.lua
  languages/unicode.lua
  tests/feat-unicode-nbsp.expected
  tests/feat-unicode-nbsp.sil
  tests/sura-2.expected
Labels: enhancement

#1937 Add retrograde package to ease version transitions by restoring old defaults
  documentation/c05-packages.sil
  packages/retrograde/init.lua
Labels: enhancement

#1941 Touchup Mac builds and Nix flake
  build-aux/pkg.nix
  justenough/macfonts.m
Labels: todo, builds & releases

#1926 fix(packages): Adjust dropcap logic for letters with a depth
  packages/dropcaps/init.lua
  tests/dropcaps-descenders.expected
  tests/dropcaps-descenders.sil
Labels: bug
