Repository sile-typesetter/sile, pull requests merged in 2023-04, with the labels that each got.

#1759 Add quiet mode flag
  core/break.lua
  core/cli.lua
  core/sile.lua
  core/utilities.lua
  packages/folio/init.lua
  sile.in
Labels: enhancement

#1763 Add more in-code comments on computeLineRatio
  typesetters/base.lua
Labels: documentation

#1765 Support initializing fill glues with a width
  core/nodefactory.lua
Labels: enhancement

#1768 docs(manual): Add section on measurements and lengths
  documentation/c04-useful.sil
  documentation/c09-concepts.sil
  languages/fr.lua
Labels: documentation

#1766 Fix subsequent line disappearing when a break occurs on a blank line
  classes/book.lua
  tests/bug-479-line-disappear.expected
  tests/bug-479-line-disappear.sil
  typesetters/base.lua
Labels: bug

#1760 Hack for parindent scoping
  classes/book.lua
  classes/plain.lua
  core/settings.lua
  tests/bug-1699.expected
  tests/bug-1699.sil
  tests/bug-192.expected
  tests/bug-262.expected
  tests/bug-39.expected
  tests/chapterverse.expected
  tests/disappearing-skip.expected
  typesetters/base.lua
Labels: bug

#1780 Fix --makedeps to play along without explicit --output
  core/makedeps.lua
  outputters/base.lua
  outputters/cairo.lua
  outputters/debug.lua
  outputters/dummy.lua
  outputters/libtexpdf.lua
  outputters/podofo.lua
  outputters/text.lua
Labels: bug

#1781 docs(manual,packages): Make packages docs independent from the SILE manual
  documentation/c01-whatis.sil
  documentation/c02-gettingstarted.sil
  documentation/c03-input.sil
  documentation/c04-useful.sil
  documentation/c05-packages.sil
  documentation/c06-macroscommands.sil
  documentation/c07-settings.sil
  documentation/c08-language.sil
  documentation/c09-concepts.sil
  documentation/c11-xmlproc.sil
  documentation/c12-tricks.sil
  documentation/macros.sil
  packages/autodoc/init.lua
  packages/chapterverse/init.lua
  packages/chordmode/init.lua
  packages/counters/init.lua
  packages/font-fallback/init.lua
  packages/gutenberg/init.lua
  packages/infonode/init.lua
  packages/leaders/init.lua
  packages/lorem/init.lua
  packages/math/init.lua
  packages/rebox/init.lua
  packages/rules/init.lua
  packages/specimen/init.lua
  packages/tableofcontents/init.lua
  packages/textcase/init.lua
  packages/verbatim/init.lua
Labels: documentation

#1778 Rewriting of the manual's chapter 10 (designing packages and classes)
  documentation/c10-classdesign.sil
  packages/autodoc/init.lua
  packages/base.lua
  packages/svg/init.lua
Labels: documentation

#1791 Bring build system and other tweaks in from Rust branch
  .cirrus.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  .gitignore
  .luacheckrc
  .luarc.json
  Makefile.am
  build-aux/list-dist-files.sh.in
  configure.ac
  core/cli.lua
  core/pathsetup.lua.in
  core/sile.lua
  flake.lock
  sile-dev-1.rockspec
  sile.in
  sile.rockspec.in
Labels: builds & releases

#1777 ci(build): Get libtexpdf into build using flake inputs
  .cirrus.yml
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  Makefile.am
  configure.ac
  flake.lock
  flake.nix
  libtexpdf.git-rev
Labels: builds & releases

#1793 Avoid stack overflow in Harfbuzz module
  src/justenoughharfbuzz.c
Labels: bug
