Repository sile-typesetter/sile, pull requests merged in 2023-11, with the labels that each got.

#1910 Remove code soon to be inaccessable because of deprecations
  core/cli.lua
  core/deprecations.lua
  core/pagebuilder.lua
  core/settings.lua
  core/sile.lua
  core/typesetter.lua
  packages/balanced-frames/init.lua
  packages/bibtex/init.lua
  packages/counters/init.lua
  packages/infonode/init.lua
  packages/masters/init.lua
  packages/rules/init.lua
  packages/twoside/init.lua
Labels: todo

#1908 Rehash how package idempotency vs. usability works
  classes/base.lua
  packages/base.lua
Labels: packages

#1895 Add configure time option to embed all resources in a single binary
  .github/workflows/build.yml
  .github/workflows/test.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile.am
  build-aux/build.rs
  configure.ac
  hooks/build
  justenough/Makefile.am
  justenough/compat-5.3.c
  justenough/compat-5.3.h
  justenough/fontmetrics.c
  justenough/hb-utils.c
  justenough/imagebbox.c
  justenough/justenoughfontconfig.c
  justenough/justenoughharfbuzz.c
  justenough/justenoughicu.c
  justenough/justenoughlibtexpdf.c
  justenough/macfonts.m
  justenough/svg.c
  src/embed.rs.in
  src/lib.rs
Labels: enhancement, builds & releases

#1792 Automated italic correction heuristics
  documentation/c07-settings.sil
  justenough/justenoughharfbuzz.c
  languages/fr.lua
  shapers/harfbuzz.lua
  tests/feat-italic-correction.expected
  tests/feat-italic-correction.sil
  typesetters/base.lua
Labels: enhancement

#1891 Use OpenType +ruby feature for ruby, toggle with setting
  Makefile-fonts
  packages/ruby/init.lua
  tests/bug-1047.expected
  tests/bug-1047.sil
  tests/bug-524.expected
  tests/bug-524.sil
  tests/bug-525.expected
  tests/bug-525.sil
  tests/bug-926.expected
  tests/bug-926.sil
Labels: enhancement

#1915 Update Arch Linux package URL in README.md
  README.md
Labels: documentation
