Repository sile-typesetter/sile, pull requests merged in 2023-05, with the labels that each got.

#1797 fix(packages): Converters package no longer worked after 0.13.0
  packages/converters/init.lua
Labels: bug

#1738 Handle multiple input documents
  core/cli.lua
  core/sile.lua
  documentation/c01-whatis.sil
  documentation/c02-gettingstarted.sil
  documentation/c10-classdesign.sil
  documentation/c12-tricks.sil
  sile.in
Labels: enhancement

#1794 Revamping the manual's chapter 5
  documentation/c02-gettingstarted.sil
  documentation/c05-packages.sil
  documentation/c10-classdesign.sil
  packages/autodoc/init.lua
  packages/chordmode/init.lua
  packages/color-fonts/init.lua
  packages/converters/init.lua
  packages/features/init.lua
  packages/footnotes/init.lua
  packages/frametricks/init.lua
  packages/gutenberg/init.lua
  packages/image/init.lua
  packages/lorem/init.lua
  packages/math/init.lua
  packages/pullquote/init.lua
  packages/raiselower/init.lua
  packages/twoside/init.lua
  packages/unichar/init.lua
Labels: documentation

#1808 Add Cantonese and Standard Chinese Translations
  i18n/ja.ftl
  i18n/yue.ftl
  i18n/zh-hans.ftl
  i18n/zh-hant.ftl
  tests/bug-990.expected
Labels: enhancement

#1805 Try to clarify that SILE doesn't require a custom input language
  documentation/c01-whatis.sil
  documentation/c02-gettingstarted.sil
  documentation/c03-input.sil
Labels: documentation
