Repository sile-typesetter/sile, pull requests merged in 2023-07, with the labels that each got.

#1826 Cleanup CI runners
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/nix.yml
  .github/workflows/test.yml
Labels: ci

#1829 Updated Fedora section in README.md
  README.md
Labels: documentation

#1832 Report on system ICU version and adjust tests accordingly
  spec/utilities_spec.lua
  src/justenoughicu.c
Labels: todo, ci
