Repository sile-typesetter/sile, pull requests merged in 2023-03, with the labels that each got.

#1725 Cast debug value to string
  packages/infonode/init.lua
Labels: bug

#1730 fix(packages): Text conversion in bookmarks has spacing issues
  packages/tableofcontents/init.lua
Labels: enhancement

#1734 Fix a typo
  README.md
  documentation/c02-gettingstarted.sil
Labels: documentation

#1712 Documentation fixes (no code changed):
  documentation/c01-whatis.sil
  documentation/c02-gettingstarted.sil
  documentation/c03-input.sil
  documentation/c04-useful.sil
  documentation/c05-packages.sil
  documentation/c06-macroscommands.sil
  documentation/c07-settings.sil
  documentation/c08-language.sil
  documentation/c09-concepts.sil
  documentation/c10-classdesign.sil
  documentation/c11-xmlproc.sil
  documentation/c12-tricks.sil
  documentation/developers.sil
  packages/autodoc/init.lua
  packages/background/init.lua
  packages/balanced-frames/init.lua
  packages/bibtex/init.lua
  packages/bidi/init.lua
  packages/boustrophedon/init.lua
  packages/break-firstfit/init.lua
  packages/chordmode/init.lua
  packages/color/init.lua
  packages/converters/init.lua
  packages/counters/init.lua
  packages/cropmarks/init.lua
  packages/date/init.lua
  packages/debug/init.lua
  packages/dropcaps/init.lua
  packages/features/init.lua
  packages/folio/init.lua
  packages/font-fallback/init.lua
  packages/footnotes/init.lua
  packages/frametricks/init.lua
  packages/grid/init.lua
  packages/gutenberg/init.lua
  packages/hanmenkyoshi/init.lua
  packages/image/init.lua
  packages/infonode/init.lua
  packages/linespacing/init.lua
  packages/lists/init.lua
  packages/masters/init.lua
  packages/math/init.lua
  packages/parallel/init.lua
  packages/pdf/init.lua
  packages/pullquote/init.lua
  packages/raiselower/init.lua
  packages/rebox/init.lua
  packages/rotate/init.lua
  packages/rules/init.lua
  packages/tableofcontents/init.lua
  packages/twoside/init.lua
  packages/unichar/init.lua
  packages/url/init.lua
  packages/xmltricks/init.lua
  sile.1.in
Labels: documentation

#1717 Avoid justification issues with relative parindent
  classes/base.lua
Labels: bug

#1709 Urlstyle hook in url package and code command moved to plain class
  classes/plain.lua
  packages/url/init.lua
  tests/feat-urlstyle.expected
  tests/feat-urlstyle.sil
Labels: enhancement

#1739 Strip content position in ToC entries
  core/utilities.lua
  documentation/c10-classdesign.sil
  packages/tableofcontents/init.lua
Labels: enhancement

#1737 Let --help be a success if called explicitly
  core/cli.lua
Labels: todo

#1743 docs: Update manual for deprecated uses of SILE.registerCommand()
  documentation/c10-classdesign.sil
  documentation/c12-tricks.sil
Labels: documentation

#1753 docs(manual): Reword introductory sections in a more neutral way
  documentation/c01-whatis.sil
Labels: documentation

#1702 Support migrating content in hbox building logic
  classes/base.lua
  classes/plain.lua
  core/nodefactory.lua
  documentation/c05-packages.sil
  documentation/c12-tricks.sil
  packages/chordmode/init.lua
  packages/cropmarks/init.lua
  packages/dropcaps/init.lua
  packages/frametricks/init.lua
  packages/gutenberg/init.lua
  packages/leaders/init.lua
  packages/lists/init.lua
  packages/pdf/init.lua
  packages/pullquote/init.lua
  packages/rebox/init.lua
  packages/rotate/init.lua
  packages/ruby/init.lua
  packages/rules/init.lua
  packages/scalebox/init.lua
  packages/simpletable/init.lua
  packages/tate/init.lua
  tests/bug-583.expected
  tests/bug-583.sil
  typesetters/base.lua
Labels: bug

#1744 new typesetter instance shall not reset settings
  core/settings.lua
  tests/bidi.sil
  tests/bug-1708.expected
  tests/bug-1708.sil
  typesetters/base.lua
Labels: bug

#1751 Get un-numbered chapters back in the ToC
  classes/book.lua
  packages/infonode/init.lua
Labels: bug
