Repository sile-typesetter/sile, pull requests merged in 2023-01, with the labels that each got.

#1682 Correct coverage stats
  .github/workflows/coverage.yml
  .luacov
Labels: ci

#1686 Package license file for vendored lunamark fork
  Makefile.am
Labels: bug, builds & releases

#1679 Use `luaEnv` properly in Nix Flake
  flake.nix
Labels: todo, builds & releases

#1681 Fixup math font loader to work with Fira family
  packages/math/base-elements.lua
  packages/math/init.lua
  tests/bug-1495-inline-math-layout.expected
  tests/bug-1495-math-alone.expected
  tests/math-bigops.expected
  tests/math-fractions.expected
  tests/math-macros.expected
  tests/math-ops.expected
  tests/math-spaces.expected
  tests/math-stretchy.expected
  tests/math-subsup.expected
  tests/math-tables-mathml.expected
  tests/math-tables-tex.expected
  tests/math-variants.expected
Labels: bug, packages

#1694 Fix lists package bug
  packages/folio/init.lua
  packages/lists/init.lua
Labels: bug

#1696 Coerce option values to booleans
  classes/base.lua
Labels: bug

#1697 Add docs for new font variations support
  documentation/c04-useful.sil
  packages/autodoc/init.lua
Labels: documentation

#1703 Update Cairo/Podofo hbox debug API to match libtexpdf
  outputters/base.lua
  outputters/cairo.lua
  outputters/podofo.lua
Labels: bug
