Repository sile-typesetter/sile, pull requests merged in 2023-09, with the labels that each got.

#1858 Cleanup warning outputs
  core/utilities.lua
  packages/tableofcontents/init.lua
Labels: bug

#1859 Add strings to pt.ftl
  i18n/pt.ftl
Labels: bug

#1863 Fix SILE.require() to generate normal Lua module specs
  core/sile.lua
Labels: bug

#1762 The SILE you know, but Rust-ier.
  .cargo/config.toml
  .cirrus.yml
  .github/workflows/build.yml
  .github/workflows/rust_lint.yml
  .github/workflows/test.yml
  .gitignore
  .luacheckrc
  .luarc.json
  Cargo.lock
  Cargo.toml
  Makefile-luarocks
  Makefile.am
  build-aux/build.rs
  build-aux/cargo-updater.js
  configure.ac
  core/cli.lua
  core/pathsetup.lua.in
  flake.nix
  package.json
  rust-toolchain
  sile-lua.1.in
  src/bin/sile.rs
  src/cli.rs
  src/lib.rs
Labels: builds & releases

#1872 Use system Lua package path from build time in run-time Rust CLI
  .cargo/config.toml
  Makefile-luarocks
  configure.ac
  core/pathsetup.lua.in
Labels: todo
