Repository sile-typesetter/sile, pull requests merged in 2024-12, with the labels that each got.

#2184 Math overset/underset and munder/mover spacing
  packages/math/base-elements.lua
  packages/math/texlike.lua
  tests/math-underset-overset.expected
  tests/math-underset-overset.sil
Labels: bug, enhancement

#2186 Sync Flake with nix derivation changes for easier extension of available Lua modules
  build-aux/ax_lua_require.m4
  build-aux/pkg.nix
  flake.lock
Labels: tooling

#2188 Properly format errors, avoid erroring after already triggering an error
  .luacheckrc
  Cargo.lock
  Cargo.toml
  core/sile.lua
  core/utilities/init.lua
  outputters/libtexpdf.lua
  rusile.rockspec.in
  src/bin/sile.rs
  src/embed.rs.in
  src/lib.rs
Labels: enhancement, tooling

#2187 feat(math): Minimal support for accents in MathML and TeX-like commands
  packages/math/atoms.lua
  packages/math/base-elements.lua
  packages/math/init.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
  packages/math/unicode-accents.lua
  packages/math/unicode-symbols.lua
Labels: bug, enhancement

#2192 Fixup macOS specific issues
  .github/workflows/build.yml
  Makefile.am
  build-aux/module.rs
  build-aux/que_rust_boilerplate.m4
  build-aux/que_rust_module.am
  configure.ac
  core/cli.lua
  core/fontmanager.lua
  core/pathsetup.lua.in
  core/sile.lua
  inputters/lua_spec.lua
  inputters/sil_spec.lua
  inputters/xml_spec.lua
  packages/counters/counters_spec.lua
  rusile/Cargo.toml
  spec/complex_frame_spec.lua
  spec/fontmanager_spec.lua
  spec/hyphenator_spec.lua
  spec/opentype_spec.lua
  spec/shaper_spec.lua
  src/lib.rs
Labels: bug, ci, tooling

#2190 Cleanup XML input before processing
  inputters/xml.lua
  inputters/xml_spec.lua
Labels: todo

#2191 Add verbatim handler for raw, touchup docs
  packages/verbatim/init.lua
Labels: enhancement, documentation, modules:packages

#2195 Sync autoconf macros with new form submitted upstream
  build-aux/ax_require_prog.m4
  build-aux/que_dist_checksums.m4
  build-aux/que_docker_boilerplate.m4
  build-aux/que_font.m4
  build-aux/que_git_version.m4
  build-aux/que_progvar.m4
  build-aux/que_rust_boilerplate.m4
  build-aux/que_subst_man_date.m4
  build-aux/que_transform_package_name.m4
  configure.ac
Labels: tooling

#2201 Distribute and install CSL support files
  build-aux/list-distfiles.sh.in
Labels: bug, tooling

#2198 Fix empty output regression
  core/utilities/init.lua
  outputters/base.lua
  outputters/debug.lua
  outputters/libtexpdf.lua
  outputters/text.lua
Labels: bug
