Repository sile-typesetter/sile, pull requests merged in 2024-01, with the labels that each got.

#1949 Fix french handling of U+00A0 (nbsp)
  languages/fr.lua
  tests/feat-unicode-nbsp.expected
Labels: bug

#1853 Another approach to full bleed printing, paper/sheet size, and pdf refactoring
  classes/base.lua
  documentation/c03-input.sil
  outputters/base.lua
  outputters/libtexpdf.lua
  packages/background/init.lua
  packages/cropmarks/init.lua
  packages/pdf/init.lua
  packages/rotate/init.lua
  packages/scalebox/init.lua
  packages/url/init.lua
  tests/bug-337.expected
  tests/bug-337.sil
  tests/bug-353.sil
  typesetters/base.lua
Labels: enhancement

#1922 Add deprecation notice to \script
  classes/base.lua
  core/utilities/init.lua
  documentation/c04-useful.sil
  tests/bug-1442-fallback-font-options.sil
  tests/bug-337.sil
  tests/dropcaps.sil
  tests/math-ops.sil
  tests/math-spaces.sil
Labels: todo

#1932 Change default parindent
  core/settings.lua
  packages/retrograde/init.lua
  tests/absmin.expected
  tests/bug-1699.sil
  tests/bug-244.expected
  tests/bug-244.sil
  tests/bug-522.sil
  tests/bug-892.sil
  tests/crash.sil
  tests/hyph-except.sil
  tests/italic.sil
  tests/parallel.sil
  tests/vertical.expected
  tests/vertical.sil
Labels: todo

#1913 Em-nesting, alignment-nesting, greek arithmetic numbering
  classes/plain.lua
  documentation/c03-input.sil
  documentation/c04-useful.sil
  documentation/c10-classdesign.sil
  packages/retrograde/init.lua
  tests/alignment.expected
  tests/alignment.sil
  tests/bug-1003.expected
  tests/bug-182.expected
  tests/bug-301.expected
Labels: enhancement

#1962 Fix polish compound hyphen rule
  documentation/c08-language.sil
  languages/pl.lua
  tests/fix-polish-hyphen.expected
  tests/fix-polish-hyphen.sil
Labels: bug

#1959 feat(typesetters): Support for speaker change introduced by em-dash
  documentation/c07-settings.sil
  tests/feat-emdash-dialogue.expected
  tests/feat-emdash-dialogue.sil
  typesetters/base.lua
Labels: enhancement

#1969 Accommodate alternative Turkish hyphenation rules
  core/hyphenator-liang.lua
  documentation/c08-language.sil
  languages/tr.lua
  tests/bug-283.expected
  tests/bug-283.sil
  tests/bug-355-tr-hyphenation.expected
  tests/bug-355-tr-hyphenation.sil
  tests/turkish-hypenation-options.expected
  tests/turkish-hypenation-options.sil
Labels: enhancement

#1970 Move language specific hyphenation handling to language modules
  core/hyphenator-liang.lua
  languages/ca.lua
  languages/fr.lua
  languages/tr.lua
  languages/unicode.lua
Labels: refactor

#1715 Overhaul SIL parser, write formal grammar
  Makefile.am
  core/settings.lua
  core/sile.lua
  core/utilities/init.lua
  documentation/c03-input.sil
  inputters/lua.lua
  inputters/sil-epnf.lua
  inputters/sil.lua
  inputters/sil_spec.lua
  packages/autodoc/init.lua
  packages/lists/init.lua
  packages/masters/init.lua
  packages/math/texlike.lua
  packages/pandoc/init.lua
  sil.abnf
  tests/bug-1715.expected
  tests/bug-1715.sil
Labels: todo

#1979 Store instantiated packages not just module source
  classes/base.lua
  core/sile.lua
  inputters/base.lua
Labels: todo

#1950 Balancing in command makecolums set as an option
  packages/frametricks/init.lua
Labels: modules:packages
