Repository sile-typesetter/sile, pull requests merged in 2024-11, with the labels that each got.

#2072 Setup Lua module for exporting Rust functions to Lua
  .commitlintrc.yml
  Cargo.lock
  Cargo.toml
  Makefile.am
  build-aux/que_rust_boilerplate.am
  configure.ac
  core/utilities/init.lua
  lua-libraries/semver.lua
  packages/retrograde/init.lua
  rusile/Cargo.toml
  rusile/src/lib.rs
  spec/rusile_spec.lua
  src/embed.rs.in
  src/lib.rs
  src/types.rs
  src/types/semver.rs
Labels: enhancement, tooling

#2151 Math more fixes and features
  packages/math/base-elements.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
  tests/bug-1495-inline-math-layout.expected
  tests/feat-math-display-numbered.expected
  tests/math-bigops.expected
  tests/math-macros.expected
  tests/math-tables-mathml.expected
  tests/math-tables-tex.expected
  tests/math-variants.expected
  types/unit.lua
Labels: bug, enhancement

#2129 Test and fix verbatim line handling
  packages/autodoc/init.lua
  packages/verbatim/init.lua
  tests/bug-132.expected
  tests/verbatim-lines.expected
  tests/verbatim-lines.sil
  typesetters/base.lua
Labels: bug

#2081 Tweak Flake to sync with Nix pkgs
  build-aux/pkg.nix
Labels: tooling

#2158 Add chunk names to load code sideloading
  inputters/lua.lua
  packages/tableofcontents/init.lua
Labels: todo

#2159 Accommodate vendored 'system' luarocks for Homebrew et al
  configure.ac
  core/pathsetup.lua.in
Labels: todo

#2163 feat(math): Support MathML movablelimits attribute
  packages/math/base-elements.lua
  packages/math/texlike.lua
  packages/math/unicode-symbols.lua
Labels: enhancement

#2136 Update autoconf macros as merged upstream"
  build-aux/ax_lua.m4
  build-aux/ax_lua_module.m4
  configure.ac
Labels: todo, tooling

#2161 feat(math): Support mathvariant on special extra greek characters
  packages/math/texlike.lua
  packages/math/unicode-mathvariants.lua
Labels: enhancement

#2162 fix(math): Avoid page breaks before display math equations
  packages/math/init.lua
  packages/math/typesetter.lua
Labels: bug

#2165 feat(math): Support MathML bevelled fractions
  packages/math/base-elements.lua
  packages/math/typesetter.lua
Labels: enhancement

#2064 Export env language var matching document state
  core/settings.lua
  spec/languages_spec.lua
  spec/rusile_spec.lua
  spec/utilities_spec.lua
  src/lib.rs
Labels: enhancement

#2175 Bump AX macros again as submitted upstream
  .cirrus.yml
  build-aux/ax_lua_module.m4
  build-aux/ax_lua_require.m4
  build-aux/ax_luarocks_rock.m4
  build-aux/pkg.nix
  build-aux/que_progvar.m4
  configure.ac
  flake.nix
Labels: tooling

#2174 Fix math primes and asterisk
  packages/math/base-elements.lua
  packages/math/init.lua
  packages/math/texlike.lua
  tests/bug-1495-inline-math-layout.expected
  tests/feat-math-display-numbered.expected
  tests/feat-math-display-unnumbered.expected
  tests/math-bigops.expected
  tests/math-fractions.expected
  tests/math-macros.expected
  tests/math-primes-asterisk.expected
  tests/math-primes-asterisk.sil
  tests/math-spaces.expected
  tests/math-stretchy.expected
  tests/math-subsup.expected
  tests/math-tables-mathml.expected
  tests/math-tables-tex.expected
  tests/math-variants.expected
Labels: bug, enhancement

#2167 feat(math): Support the MathML operator dictionary and many TeX-like aliases
  Makefile-fonts
  Makefile.am
  build-aux/pkg.nix
  build-aux/xml-entities-to-lua.xsl
  configure.ac
  packages/math/atoms.lua
  packages/math/base-elements.lua
  packages/math/init.lua
  packages/math/mathml-entities.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
  packages/math/unicode-symbols.lua
  tests/math-ops.sil
  tests/math-predefined-tex-functions.expected
  tests/math-predefined-tex-functions.sil
  tests/math-unary-binary-minus.expected
  tests/math-unary-binary-minus.sil
  tests/math-variants.expected
  tests/math-variants.xml
Labels: enhancement

#2177 fix(math): Suppress invisible operators in MathML
  packages/math/typesetter.lua
Labels: bug

#2179 Support TeX-like left..right construct
  packages/math/init.lua
  packages/math/texlike.lua
  tests/math-left-right-tex.expected
  tests/math-left-right-tex.sil
Labels: enhancement

#2178 Support cross-compilation environments
  Makefile.am
  build-aux/que_rust_boilerplate.am
  build-aux/que_rust_boilerplate.m4
Labels: todo, tooling

#2180 Patch up autodoc code blocks
  packages/autodoc/init.lua
  tests/verbatim-lines.expected
  tests/verbatim-lines.sil
Labels: documentation

#2082 CSL support
  packages/bibtex/csl/csl_spec.lua
  packages/bibtex/csl/engine.lua
  packages/bibtex/csl/locale.lua
  packages/bibtex/csl/locales/README.md
  packages/bibtex/csl/locales/locales-en-US.xml
  packages/bibtex/csl/locales/locales-fr-FR.xml
  packages/bibtex/csl/style.lua
  packages/bibtex/csl/styles/README.md
  packages/bibtex/csl/styles/chicago-author-date-fr.csl
  packages/bibtex/csl/styles/chicago-author-date.csl
  packages/bibtex/csl/utils/casing.lua
  packages/bibtex/csl/utils/superfolding.lua
  packages/bibtex/csl/utils/xmlparser.lua
  packages/bibtex/init.lua
  packages/bibtex/support/bib2csl.lua
  packages/bibtex/support/locators.lua
  packages/bibtex/support/nbibtex.lua
Labels: packages:bibliography

#2183 fix(math): Erroneous capital H and I in fraktur variant
  packages/math/unicode-mathvariants.lua
Labels: bug
