Repository sile-typesetter/sile, pull requests merged in 2024-02, with the labels that each got.

#1980 Simplify discretionary logic and line ratio computation
  core/nodefactory.lua
  typesetters/base.lua
Labels: refactor

#1977 Typesetter and package support for constructs spanning multiple lines
  languages/ja.lua
  packages/color/init.lua
  packages/pdf/init.lua
  packages/rules/init.lua
  tests/bug-990.expected
  tests/feat-liner-spanning.expected
  tests/feat-liner-spanning.sil
  typesetters/base.lua
Labels: bug, enhancement

#1985 Correct discretionary width in liners
  tests/bug-liner-width.expected
  tests/bug-liner-width.sil
  typesetters/base.lua
Labels: bug

#1981 refactor(packages): Remove unused typesetter-scoped cursor tracking
  packages/raiselower/init.lua
Labels: refactor

#1983 Add active hook system to settings
  core/settings.lua
  core/settings_spec.lua
Labels: enhancement

#1997 Add debug tooling to color type
  core/utilities/init.lua
  outputters/debug.lua
  outputters/libtexpdf.lua
  packages/color-fonts/init.lua
  packages/hanmenkyoshi/init.lua
  tests/bug-1142.expected
  tests/bug-1171.expected
  tests/bug-1244-fallback-after-color.expected
  tests/bug-353.expected
  tests/bug-524.expected
  tests/bug-865.expected
  tests/bug-liner-width.expected
  tests/bug-liner-width.sil
  types/color.lua
Labels: enhancement

#1995 Apply double hyphenation rules to more languages
  documentation/c08-language.sil
  languages/cs.lua
  languages/es.lua
  languages/hr.lua
  languages/pl.lua
  languages/pt.lua
  languages/sk.lua
  languages/unicode.lua
Labels: enhancement

#1998 Auto-generate Lua API documentation
  .cirrus.yml
  .commitlintrc.yml
  .editorconfig
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  Makefile.am
  build-aux/config.ld
  build-aux/pkg.nix
  classes/base.lua
  configure.ac
  core/deprecations.lua
  core/font.lua
  core/globals.lua
  core/languages.lua
  core/settings.lua
  core/sile.lua
  core/utilities/ast.lua
  core/utilities/init.lua
  core/utilities/numbers.lua
  core/utilities/sorting.lua
  inputters/base.lua
  languages/fr.lua
  outputters/base.lua
  packages/base.lua
  packages/bibtex/bibliography.lua
  pagebuilders/base.lua
  shapers/base.lua
  types/color.lua
  types/length.lua
  types/measurement.lua
  types/node.lua
  types/unit.lua
  typesetters/base.lua
Labels: documentation
