Repository sile-typesetter/sile, pull requests merged in 2024-10, with the labels that each got.

#2105 Extend SU.collatedSort for complex table sorting
  core/utilities/sorting.lua
  justenough/justenoughicu.c
  spec/utilities_spec.lua
Labels: enhancement

#2119 feat(math): Support square roots
  packages/math/base-elements.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
Labels: modules:packages

#2125 feat(languages): Add bibliography localizations for Swedish
  languages/sv/messages.ftl
Labels: enhancement

#2113 Fix syntax tree differences between commands and environments
  core/sile.lua
  core/utilities/ast.lua
  inputters/base.lua
  inputters/sil.lua
  inputters/sil_spec.lua
  packages/autodoc/init.lua
Labels: bug, enhancement

#2137 Fix handling of --option flag in Rust CLI
  src/cli.rs
  src/lib.rs
Labels: bug

#2103 Updated Fedora Linux in README.md
  README.md
Labels: documentation

#2135 fix(packages): Correct math greek symbols and their var-alternate
  packages/math/unicode-symbols.lua
  tests/math-bigops.xml
Labels: bug

#2139 TeX-math limits and other commands behaving as big ops
  packages/math/texlike.lua
Labels: enhancement

#2140 feat(math): Support MathML mtext and ms elements
  packages/math/base-elements.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
Labels: enhancement

#2142 fix(math): Fractions must have padding to avoid visual confusion
  packages/math/base-elements.lua
  tests/math-bigops.expected
  tests/math-fractions.expected
  tests/math-macros.expected
  tests/math-stretchy.expected
Labels: bug

#2143 Support MathML mphantom and TeX-like phantom, hphantom, vphantom
  packages/math/base-elements.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
Labels: enhancement

#2141 Support MathML mroot
  packages/math/base-elements.lua
  packages/math/typesetter.lua
  shapers/base.lua
Labels: enhancement

#2147 Fix math mathvariants
  packages/math/base-elements.lua
  packages/math/texlike.lua
  packages/math/typesetter.lua
  packages/math/unicode-mathvariants.lua
  tests/bug-1495-inline-math-layout.expected
  tests/feat-math-display-numbered.expected
  tests/feat-math-display-unnumbered.expected
  tests/math-bigops.expected
  tests/math-macros.expected
  tests/math-stretchy.expected
  tests/math-stretchy.xml
  tests/math-subsup.expected
Labels: bug
