Repository sile-typesetter/sile, pull requests merged in 2025-04, with the labels that each got.

#2248 Normalize module layout across all module types
  classes/base.lua
  classes/plain.lua
  classes/tplain.lua
  core/init.lua
  core/languages.lua
  core/loaders.lua
  core/misc.lua
  core/process.lua
  core/require.lua
  core/sile.lua
  core/use.lua
  core/utilities/init.lua
  documentation/c10-classdesign.sil
  inputters/base.lua
  packages/background/init.lua
  packages/counters/init.lua
  packages/footnotes/init.lua
  packages/image/init.lua
  packages/url/init.lua
  shapers/base.lua
  shapers/harfbuzz.lua
  typesetters/base.lua
Labels: todo, refactor

#2259 Fix hyphen minima logic and update several hyphenation patterns
  core/hyphenator-liang.lua
  languages/bg/hyphens-tex.lua
  languages/bg/hyphens.lua
  languages/bg/init.lua
  languages/el/hyphens-tex.lua
  languages/el/init.lua
  languages/en/hyphens.lua
  languages/eo/hyphens.lua
  languages/es/hyphens-tex.lua
  languages/es/init.lua
  languages/pt/hyphens-tex.lua
  languages/pt/init.lua
  languages/th/hyphens-tex.lua
  languages/th/init.lua
  languages/tr/hyphens.lua
  spec/languages_spec.lua
  tests/alignment.expected
  tests/bug-252.expected
  tests/bug-308.expected
  tests/bug-526.expected
  tests/eject.expected
  tests/fix-polish-hyphen.expected
  tests/footnote-skip.expected
  tests/footnote.expected
  tests/grid.expected
  tests/hangafter.expected
  tests/linespacing.expected
  tests/masters.expected
  tests/parshaping-simple.expected
  tests/split-footnote.expected
Labels: bug

#2257 Allow unused argument self in Lua linter
  .luacheckrc
  classes/base.lua
  classes/plain.lua
  core/break.lua
  inputters/base.lua
  inputters/lua.lua
  inputters/xml.lua
  languages/fr/init.lua
  languages/unicode/init.lua
  outputters/base.lua
  outputters/cairo.lua
  outputters/debug.lua
  outputters/libtexpdf.lua
  outputters/podofo.lua
  outputters/text.lua
  packages/autodoc/init.lua
  packages/base.lua
  packages/bibtex/init.lua
  packages/bidi/init.lua
  packages/chordmode/init.lua
  packages/complex-spaces/init.lua
  packages/converters/init.lua
  packages/counters/init.lua
  packages/date/init.lua
  packages/dropcaps/init.lua
  packages/folio/init.lua
  packages/frametricks/init.lua
  packages/inputfilter/init.lua
  packages/insertions/init.lua
  packages/linespacing/init.lua
  packages/lists/init.lua
  packages/math/base-elements.lua
  packages/math/init.lua
  packages/retrograde/init.lua
  packages/ruby/init.lua
  packages/tableofcontents/init.lua
  packages/twoside/init.lua
  packages/url/init.lua
  pagebuilders/base.lua
  pagebuilders/grid.lua
  shapers/base.lua
  shapers/fallback.lua
  shapers/harfbuzz.lua
  shapers/pango.lua
  types/color.lua
  types/node.lua
  typesetters/base.lua
  typesetters/tate.lua
Labels: refactor

#2267 Feat: Support CSL position condition
  packages/bibtex/csl/engine.lua
  packages/bibtex/init.lua
Labels: packages:bibliography

#2271 Track the parent modules of commands
  classes/base.lua
  classes/book.lua
  core/commands.lua
  core/deprecations.lua
  core/font.lua
  core/misc.lua
  core/process.lua
  core/settings.lua
  core/sile.lua
  core/utilities/ast.lua
  languages/base-hyphenator.lua
  languages/base.lua
  packages/autodoc/init.lua
  packages/base.lua
  packages/converters/init.lua
  packages/cropmarks/init.lua
  packages/features/init.lua
  packages/indexer/init.lua
  packages/pandoc/init.lua
  packages/parallel/init.lua
  packages/retrograde/init.lua
  packages/tableofcontents/init.lua
  tests/bug-892.sil
  types/command.lua
Labels: enhancement, refactor
