Repository sile-typesetter/sile, pull requests merged in 2025-03, with the labels that each got.

#2238 docs(manual): Replace URLs in the documentation by actual hyperlinks
  documentation/c02-gettingstarted.sil
  documentation/c05-packages.sil
  documentation/c08-language.sil
  documentation/c13-tricks.sil
  documentation/sile.sil
  packages/counters/init.lua
  packages/date/init.lua
  packages/features/init.lua
  packages/inputfilter/init.lua
  packages/parallel/init.lua
Labels: documentation

#2239 Update tests for ICU changing default numbering systems
  .cirrus.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/nix.yml
  .github/workflows/test.yml
  Makefile.am
  build-aux/que_rust_boilerplate.am
  package.json
  spec/fontmanager_spec.lua
  spec/utilities_spec.lua
Labels: ci

#2234 fix(typesetters): Special punctuation spaces need better italic corre…
  tests/feat-italic-correction.expected
  typesetters/base.lua
Labels: bug, enhancement

#2221 feat(typesetters): Discourage page breaks after hyphenated lines
  packages/retrograde/init.lua
  typesetters/base.lua
Labels: enhancement

#2207 Overhaul indexer
  packages/indexer/init.lua
  packages/tableofcontents/init.lua
  typesetters/base.lua
Labels: bug, enhancement, modules:packages

#2228 A few simple CSL fixes
  packages/bibtex/csl/engine.lua
Labels: bug, packages:bibliography

#2224 fix(math): Script 'math' is needed for the ssty feature to work properly
  packages/math/base-elements.lua
  packages/math/init.lua
Labels: bug

#2237 feat(core): Support ex-height and cap-height font adjustment
  classes/plain.lua
  core/font.lua
  documentation/c04-useful.sil
  documentation/macros.sil
  packages/verbatim/init.lua
  tests/feat-urlstyle.expected
  tests/verbatim-lines.expected
Labels: bug, enhancement

#2210 Post vendored crates tarball
  .github/workflows/build.yml
  .gitignore
  Makefile.am
  build-aux/que_rust_boilerplate.am
  build-aux/sile_dist_checksums.m4
  configure.ac
Labels: tooling

#2240 Change load order so language warnings calm down
  core/languages.lua
  core/settings.lua
  languages/ar/hyphens.lua
  languages/ar/init.lua
  languages/bo/hyphens.lua
  languages/bo/init.lua
  languages/sd/hyphens.lua
  languages/sd/init.lua
  languages/ur/hyphens.lua
  languages/ur/init.lua
Labels: bug

#2230 More CSL features: multiple citations and paragraph format
  packages/bibtex/csl/engine.lua
  packages/bibtex/csl/style.lua
  packages/bibtex/csl/utils/superfolding.lua
  packages/bibtex/init.lua
  packages/bibtex/support/bibparser.lua
  tests/bibtex.sil
  tests/bug-2054.sil
Labels: enhancement, packages:bibliography

#2245 Fix and enhance makefile dependency list generation
  core/cli.lua
  core/makedeps.lua
  core/sile.lua
  src/lib.rs
Labels: bug, enhancement

#2244 Fixup flexible space creation logic
  packages/retrograde/init.lua
  shapers/base.lua
  tests/bug-355-tr-hyphenation.expected
Labels: bug

#2247 Remove stdlib shims and normalize typesetter module layout a bit
  .github/CODEOWNERS
  classes/base.lua
  classes/jplain.lua
  classes/tbook.lua
  classes/tplain.lua
  core/sile.lua
  core/utilities/init.lua
  documentation/c10-classdesign.sil
  documentation/c13-tricks.sil
  inputters/base.lua
  outputters/base.lua
  packages/balanced-frames/init.lua
  packages/base.lua
  packages/insertions/init.lua
  packages/parallel/init.lua
  packages/tate/init.lua
  pagebuilders/default.lua
  shapers/base.lua
  spec/break_spec.lua
  spec/complex_frame_spec.lua
  tests/bug-244.expected
  tests/classes/testsidenote.lua
  tests/classes/testtwocol.lua
  types/color.lua
  typesetters/base.lua
  typesetters/default.lua
  typesetters/latin-in-tate.lua
Labels: todo
